# Homebrew formula for rigor-rs (§13, ADR-0010 — Homebrew distribution channel,
# co-equal with the Releases/cargo-binstall and the precompiled gem).
#
# ─────────────────────────────────────────────────────────────────────────────
# THIS IS A REVIEWABLE TEMPLATE — DO NOT SHIP THE PLACEHOLDER SHA256s AS-IS.
#
# The four `sha256` values below are deliberate, obvious PLACEHOLDERS
# (64 zeros). They are NOT real hashes and a `brew install` against them WILL
# FAIL integrity verification. The release CI (`.github/workflows/release.yml`,
# the `homebrew-formula` job) regenerates this file with the REAL per-target
# sha256s (read from each `rigor-<version>-<target>.tar.gz.sha256` sidecar) and
# the real version (`${GITHUB_REF_NAME#v}`) once the GitHub Release assets exist,
# then uploads the filled formula as a release/workflow artifact.
#
# Canonical home (DEFERRED): the eventual install path is a tap repo
# `rigortype/homebrew-tap`, i.e. `brew install rigortype/tap/rigor`. Pushing the
# generated formula to that tap needs the tap repo to exist + a token, so it is
# GATED/deferred (mirrors the gem `gem push` gate). See HomebrewFormula/README.md
# and docs/CURRENT_WORK.md §13.
#
# NOTE: `https://github.com/rigortype/rigor-rs` is a PLACEHOLDER URL — no public
# repo is configured yet. Confirm when the project is published.
# ─────────────────────────────────────────────────────────────────────────────
class Rigor < Formula
  desc "Inference-first static analyzer for Ruby (Rust port of Rigor)"
  homepage "https://github.com/rigortype/rigor-rs"
  version "0.0.1"
  license "AGPL-3.0"

  # PLACEHOLDER sha256s — regenerated by release CI from the real release
  # assets. "0" * 64. Do not ship as-is (see header).
  on_macos do
    on_arm do
      # aarch64-apple-darwin
      url "https://github.com/rigortype/rigor-rs/releases/download/v#{version}/rigor-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      # x86_64-apple-darwin
      url "https://github.com/rigortype/rigor-rs/releases/download/v#{version}/rigor-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      # aarch64-unknown-linux-gnu
      url "https://github.com/rigortype/rigor-rs/releases/download/v#{version}/rigor-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      # x86_64-unknown-linux-gnu
      url "https://github.com/rigortype/rigor-rs/releases/download/v#{version}/rigor-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    # The release archive holds the bare `rigor` binary at its root.
    bin.install "rigor"
  end

  test do
    assert_match "rigor #{version}", shell_output("#{bin}/rigor --version")

    # Trivial end-to-end smoke: `rigor check` on a throwaway Ruby file.
    (testpath/"smoke.rb").write("x = 1\n")
    system bin/"rigor", "check", testpath/"smoke.rb"
  end
end
