//! Build-time embedding of the vendored RBS signature set (ADR-0007).
//!
//! Walks `vendor/rbs/` (relative to `CARGO_MANIFEST_DIR`), collects every `.rbs`
//! file, and generates `$OUT_DIR/embedded_rbs.rs` defining
//!
//! ```ignore
//! pub static EMBEDDED_RBS: &[(&str, &str)] = &[
//!     ("core/array.rbs", include_str!("<abs>/vendor/rbs/core/array.rbs")),
//!     // … one entry per vendored .rbs, in DETERMINISTIC sorted order …
//! ];
//! ```
//!
//! The entries are sorted by their relative path so the embedded order is
//! stable across machines/builds. The runtime ingest (`Builder::ingest`) is
//! order-independent for class membership — the old filesystem path used a
//! nondeterministic `read_dir` order — so any total order yields the same index;
//! we pick sorted for reproducibility.
//!
//! No external crates (offline build): std only.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let vendor_root = Path::new(&manifest_dir).join("vendor").join("rbs");

    // Collect every `.rbs` under the vendored tree, keyed by its path relative to
    // `vendor/rbs/` (forward slashes), value = absolute path for `include_str!`.
    // A BTreeMap gives a deterministic (sorted-by-relative-path) iteration order.
    let mut files: BTreeMap<String, PathBuf> = BTreeMap::new();
    collect_rbs(&vendor_root, &vendor_root, &mut files);

    assert!(
        !files.is_empty(),
        "no vendored .rbs found under {} — vendor tree missing?",
        vendor_root.display()
    );

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("/// Every vendored RBS file as `(relative-path, contents)`, in\n");
    out.push_str("/// deterministic sorted-by-path order. Embedded via `include_str!`.\n");
    out.push_str("pub static EMBEDDED_RBS: &[(&str, &str)] = &[\n");
    for (rel, abs) in &files {
        // Both literals are well-formed: `rel` is a slash-joined path of file
        // names; `abs` is an absolute filesystem path. Escape for safety.
        out.push_str("    (");
        out.push_str(&escape(rel));
        out.push_str(", include_str!(");
        out.push_str(&escape(&abs.to_string_lossy()));
        out.push_str(")),\n");
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("embedded_rbs.rs");
    std::fs::write(&dest, out).expect("write embedded_rbs.rs");

    // Rebuild when the vendored tree changes.
    println!("cargo:rerun-if-changed=vendor/rbs");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Recursively collect `.rbs` files under `dir`, keyed by path relative to `root`
/// (forward-slash separated, stable across platforms).
fn collect_rbs(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rbs(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "rbs") {
            let rel = path
                .strip_prefix(root)
                .expect("path under root")
                .components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            out.insert(rel, path);
        }
    }
}

/// Emit a Rust string literal for `s` (double-quoted, backslash/quote escaped).
fn escape(s: &str) -> String {
    let mut lit = String::with_capacity(s.len() + 2);
    lit.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => lit.push_str("\\\\"),
            '"' => lit.push_str("\\\""),
            _ => lit.push(ch),
        }
    }
    lit.push('"');
    lit
}
