#!/usr/bin/env python3
"""Generate `harness/effects-corpus/05_posture` from the VENDORED effect catalogue.

The gate this project exists for (issue #106): upstream applies a catalogue
class's `posture:` only when the typer did NOT call the receiver `Dynamic`
(`unit_scan.rb`'s `posture_allowed?`), and **the reference cannot resolve every
constant its own catalogue names** — `Net::HTTP`, `PTY`, `SOCKSSocket` and five
more are `Dynamic` there, so upstream refuses the posture and proves nothing.
A typer-free port has no such bit, so an unconditional posture tier OVER-claims
on exactly those classes. That is a live false positive in waiting
([ADR-0043](../docs/adr/0043-effect-system-port-parity-model.md) § 4), and no
existing fixture contained one of the eight classes — the fixture-corpus blind
spot again (`docs/notes/20260731-survey-fp-triage-24.md`).

**Generated, not hand-written**, for the same reason `harness/sweep-corpora.yml`
is a manifest rather than a hand-typed directory list: the eight classes are a
function of the reference's RBS environment at the PIN, and the catalogue itself
moves with the pin. A hand-list would freeze today's eight and go quietly stale;
a file generated from `crates/rigor-effects/vendor/effects/core.yml` covers every
class the catalogue names, so a re-vendor that adds a class adds its probe, and
the differential re-measures which ones the oracle can actually resolve. Nothing
here encodes WHICH constants the reference resolves — the port must not mirror
that (ADR-0043 § 1), and this file never tries to.

The source is the VENDORED copy, not `reference/rigor/data/effects/core.yml`:
the vendored bytes are what the measured binary compiles in (`include_str!`), so
the project probes exactly the catalogue under test. `vendor_effects.py --check`
is what keeps those bytes equal to the pin's.

Three sections, all derived:

  `Posture#c_*`   one method per class carrying a `posture:`, calling a selector
                  no row and no universal name claims. Only the class posture
                  can answer, so the proven lane isolates that tier.
  `Row#r_*`       the MUST-STILL-FIRE control for the row tier: the class's
                  first identifier-spelled row with plain `effects:` (no
                  `narrow:`, no `mutates:`, non-empty labels). Rows are looked up
                  BEFORE the posture and answer whatever the typer says, so
                  these must stay MATCH — including `Net::HTTP.get`, a row on a
                  class the oracle cannot resolve.
  `Universal#u_*` the MUST-STILL-FIRE control for the universal tier, on every
                  class whose posture is non-empty: the first `universal:` name
                  the class does not row. The universal list answers ∅ BEFORE
                  the posture, so a port that ever lets a posture leak past it
                  turns these into OVER rows.

Together the two control sections are why "delete the whole catalogue tier"
cannot pass this gate.

Usage:
    python3 harness/gen_effects_posture_corpus.py [--check]

    --check   do not write: regenerate in memory and compare bytes against the
              committed project, exiting 1 on any difference. The drift gate —
              a re-vendored catalogue with an unregenerated corpus fails here.
"""
import os
import re
import sys

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOGUE = os.path.join(REPO, "crates/rigor-effects/vendor/effects/core.yml")
PROJECT = os.path.join(REPO, "harness/effects-corpus/05_posture")

# The probe selector. Asserted below to be claimed by nothing but a posture:
# absent from every row of every class and from the `universal:` list, so the
# posture tier is the ONLY tier that can answer it.
PROBE_SELECTOR = "zz_uncatalogued_zz"

# A selector this generator will spell as a plain `recv.name` call. Operator and
# index rows (`[]`, `[]=`, `<<`) are deliberately skipped for the CONTROLS: they
# need their own syntax, and `01_core_origins` already carries `ENV["HOME"]`.
IDENTIFIER = re.compile(r"\A[a-z_][A-Za-z0-9_]*[?!]?\Z")

RIGOR_YML = """\
# GENERATED by harness/gen_effects_posture_corpus.py — see posture.rb.
paths:
  - .
"""

HEADER = """\
# GENERATED by `python3 harness/gen_effects_posture_corpus.py` — DO NOT EDIT.
#
# Source: crates/rigor-effects/vendor/effects/core.yml — the VENDORED catalogue,
# i.e. the bytes the measured binary compiles in.
# schema {schema}, vocabulary {vocabulary}, {classes} classes.
#
# The POSTURE-TIER over-claim gate (issue #106). Upstream gates a class's
# default `posture:` on the receiver's typing — `posture_allowed?` refuses it
# whenever the typer called the receiver `Dynamic` — and the reference cannot
# resolve every constant its own catalogue names. A typer-free port has no such
# bit, so an unconditional posture tier proves labels the oracle does not, which
# is an OVER and a false positive in waiting (ADR-0043 § 4).
#
# WHICH constants the oracle resolves is deliberately not encoded here: it is a
# function of the reference's RBS environment and moves with the pin AND with
# the machine, and mirroring it is forbidden (ADR-0043 § 1). The project probes
# EVERY catalogued class and lets the differential report the answer.
#
# `Posture#c_*` isolates the posture tier. `Row#r_*` and `Universal#u_*` are the
# must-still-fire controls for the two tiers consulted BEFORE it, so a port
# cannot pass by dropping the catalogue altogether.
"""


def load_catalogue():
    with open(CATALOGUE, encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def bucket_of(body):
    """The row bucket a `Konstant.selector` call looks up.

    A `kind: object` constant (`ENV`, `STDOUT`, …) names an OBJECT, so the call
    is an INSTANCE dispatch and keys `ENV#[]`; every other constant names a
    class and keys the singleton `File.read` (`unit_scan.rb`'s `catalog_target`,
    ported at `crates/rigor-cli/src/effects/collect.rs`'s `catalog_target`).
    """
    if body.get("kind") == "object":
        return body.get("methods") or {}
    return body.get("singleton_methods") or {}


def row_control(body):
    """The class's first row that states plain, non-empty `effects:`.

    `narrow:` rows are skipped because their labels depend on the call's literal
    arguments and on whether the port implements the handler — a control must
    fail for one reason only. `mutates: receiver` rows are skipped because their
    reading is the ownership judgment, which `01_core_origins` owns.
    """
    for selector, row in sorted(bucket_of(body).items()):
        row = row or {}
        if row.get("narrow") or row.get("mutates"):
            continue
        if not (row.get("effects") or []):
            continue
        if not IDENTIFIER.match(selector):
            continue
        return selector, list(row["effects"])
    return None


def universal_control(catalogue, body):
    """The first `universal:` name the class does not row itself.

    In the catalogue's own order, which is upstream's. A rowed selector would be
    answered by the row and would grade the wrong tier.
    """
    rowed = set(bucket_of(body))
    for selector in catalogue["universal"]:
        if selector in rowed or not IDENTIFIER.match(selector):
            continue
        return selector
    return None


def slug(class_name):
    return class_name.replace("::", "__").lower()


def assert_probe_is_unclaimed(catalogue):
    if PROBE_SELECTOR in catalogue["universal"]:
        sys.exit(f"gen_effects_posture_corpus: `{PROBE_SELECTOR}` is a universal name")
    for name, body in catalogue["classes"].items():
        body = body or {}
        for key in ("methods", "singleton_methods"):
            if PROBE_SELECTOR in (body.get(key) or {}):
                sys.exit(f"gen_effects_posture_corpus: {name} rows `{PROBE_SELECTOR}`")


def section(title, prose, class_name, methods):
    """One `class … end` block with its explanatory banner."""
    rule = "-" * max(3, 72 - len(title))
    lines = [f"# --- {title} {rule}", "#"]
    lines.extend(f"# {line}".rstrip() for line in prose)
    lines.extend(["", f"class {class_name}"])
    bodies = []
    for name, call, why in methods:
        block = [f"  # {why}"] if why else []
        block.extend([f"  def {name}", f"    {call}", "  end"])
        bodies.append("\n".join(block))
    lines.append("\n\n".join(bodies))
    lines.append("end")
    return "\n".join(lines)


def render(catalogue):
    classes = catalogue["classes"]
    assert_probe_is_unclaimed(catalogue)

    slugs = {}
    for name in classes:
        slugs.setdefault(slug(name), []).append(name)
    collided = {k: v for k, v in slugs.items() if len(v) > 1}
    if collided:
        sys.exit(f"gen_effects_posture_corpus: slug collision {collided}")

    out = [HEADER.format(schema=catalogue["schema"], vocabulary=catalogue["vocabulary"],
                         classes=len(classes)).rstrip("\n")]

    postured = [(n, b or {}) for n, b in sorted(classes.items()) if (b or {}).get("posture")]
    out.append(section(
        "the posture tier, isolated",
        [f"One method per class carrying a `posture:` ({len(postured)} of {len(classes)}).",
         f"`{PROBE_SELECTOR}` is rowed by no class and is not a universal name, so a",
         "proven label here can only have come from the class default. A class whose",
         "posture resolves to ∅ is included anyway: it is an exhaustiveness probe for",
         "the taint slice, and the set of classes is the catalogue's, not a curated one."],
        "Posture",
        [(f"c_{slug(name)}", f"{name}.{PROBE_SELECTOR}", f"posture: {body['posture']}")
         for name, body in postured]))

    rows = [(n, row_control(b or {})) for n, b in sorted(classes.items())]
    rows = [(n, r) for n, r in rows if r]
    out.append(section(
        "control: the ROW tier still answers",
        ["`Catalog#lookup` reads a row BEFORE it consults the posture, and a row is",
         "authoritative whatever the typer thinks of the receiver — `Net::HTTP.get` is",
         "proven `io.net.http` by the oracle even though `Net::HTTP` is exactly the",
         "constant it cannot resolve. These must stay MATCH."],
        "Row",
        [(f"r_{slug(name)}", f"{name}.{selector}", f"{name}: {', '.join(labels)}")
         for name, (selector, labels) in rows]))

    universal = []
    for name, body in sorted(classes.items()):
        body = body or {}
        if not catalogue["defaults"].get(body.get("posture")):
            continue
        selector = universal_control(catalogue, body)
        if selector:
            universal.append((name, selector))
    out.append(section(
        "control: the UNIVERSAL tier still answers, and still WINS",
        ["The 34-name `universal:` list is consulted before the posture, and it answers",
         "∅: `File.class` touches nothing, and the oracle proves nothing for it even",
         "though `File`'s posture is `io.fs`. Every class below has a NON-EMPTY posture,",
         "so a posture that ever leaked past the universal tier would show up here as an",
         "OVER rather than as silence."],
        "Universal",
        [(f"u_{slug(name)}", f"{name}.{selector}", None) for name, selector in universal]))

    return "\n\n".join(out).rstrip("\n") + "\n", len(postured), len(rows), len(universal)


def main():
    check = "--check" in sys.argv[1:]
    if [a for a in sys.argv[1:] if a != "--check"]:
        print(__doc__)
        return 2

    catalogue = load_catalogue()
    body, n_posture, n_row, n_universal = render(catalogue)
    files = {"posture.rb": body, ".rigor.yml": RIGOR_YML}

    print(f"catalogue: {os.path.relpath(CATALOGUE, REPO)}")
    print(f"project:   {os.path.relpath(PROJECT, REPO)}")
    print(f"  posture probes   {n_posture}")
    print(f"  row controls     {n_row}")
    print(f"  universal ctrls  {n_universal}")

    if check:
        stale = []
        for name, text in sorted(files.items()):
            path = os.path.join(PROJECT, name)
            current = None
            if os.path.isfile(path):
                with open(path, encoding="utf-8") as handle:
                    current = handle.read()
            status = "ok" if current == text else ("ABSENT" if current is None else "STALE")
            print(f"  {name:<12} {status}")
            if status != "ok":
                stale.append(name)
        if stale:
            print("CHECK: the committed corpus does not match the vendored catalogue —")
            print("       regenerate with `python3 harness/gen_effects_posture_corpus.py`")
            print("       and read the diff as a CATALOGUE change.")
            return 1
        print("CHECK: the committed corpus matches the vendored catalogue exactly.")
        return 0

    os.makedirs(PROJECT, exist_ok=True)
    for name, text in sorted(files.items()):
        with open(os.path.join(PROJECT, name), "w", encoding="utf-8") as handle:
            handle.write(text)
    print("written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
