//! GENERATED by `ruby harness/conformance_load_set.rb --write`; verify with
//! `--check` (a pin-bump and host-gem ritual, like `unbuildable_classes.rb`).
//! Do not edit by hand. Derived from the pinned reference's default
//! environment on the gate host: 897 names.

/// Names whose view differs between the port's recorded RBS model and the
/// reference's default environment (see the generator's header). The
/// `conforms-to` scan never resolves through, trusts, or orders by one.
pub(super) const LOAD_SET_DIVERGENT: &[&str] = &[
    "BigDecimal", // instance surface: reference-only ["to_digits"], port-only []
    "BigDecimal::round_mode", // type alias on the reference only
    "BigDecimal::round_mode_integer", // type alias on the reference only
    "BigDecimal::round_mode_symbol", // type alias on the reference only
    "BigMath", // instance surface: reference-only ["expm1", "log10", "log1p"]…, port-only []
    "Prism", // reference-only module
    "Prism::ASCIISource", // reference-only class
    "Prism::AliasGlobalVariableNode", // reference-only class
    "Prism::AliasMethodNode", // reference-only class
    "Prism::AlternationPatternNode", // reference-only class
    "Prism::AndNode", // reference-only class
    "Prism::ArgumentsNode", // reference-only class
    "Prism::ArgumentsNodeFlags", // reference-only module
    "Prism::ArgumentsNodeFlags::CONTAINS_FORWARDING", // constant on the reference only
    "Prism::ArgumentsNodeFlags::CONTAINS_KEYWORDS", // constant on the reference only
    "Prism::ArgumentsNodeFlags::CONTAINS_KEYWORD_SPLAT", // constant on the reference only
    "Prism::ArgumentsNodeFlags::CONTAINS_MULTIPLE_SPLATS", // constant on the reference only
    "Prism::ArgumentsNodeFlags::CONTAINS_SPLAT", // constant on the reference only
    "Prism::ArrayNode", // reference-only class
    "Prism::ArrayNodeFlags", // reference-only module
    "Prism::ArrayNodeFlags::CONTAINS_SPLAT", // constant on the reference only
    "Prism::ArrayPatternNode", // reference-only class
    "Prism::AssocNode", // reference-only class
    "Prism::AssocSplatNode", // reference-only class
    "Prism::BACKEND", // constant on the reference only
    "Prism::BackReferenceReadNode", // reference-only class
    "Prism::BasicVisitor", // reference-only class
    "Prism::BeginNode", // reference-only class
    "Prism::BlockArgumentNode", // reference-only class
    "Prism::BlockLocalVariableNode", // reference-only class
    "Prism::BlockNode", // reference-only class
    "Prism::BlockParameterNode", // reference-only class
    "Prism::BlockParametersNode", // reference-only class
    "Prism::BreakNode", // reference-only class
    "Prism::CallAndWriteNode", // reference-only class
    "Prism::CallNode", // reference-only class
    "Prism::CallNodeFlags", // reference-only module
    "Prism::CallNodeFlags::ATTRIBUTE_WRITE", // constant on the reference only
    "Prism::CallNodeFlags::IGNORE_VISIBILITY", // constant on the reference only
    "Prism::CallNodeFlags::SAFE_NAVIGATION", // constant on the reference only
    "Prism::CallNodeFlags::VARIABLE_CALL", // constant on the reference only
    "Prism::CallOperatorWriteNode", // reference-only class
    "Prism::CallOrWriteNode", // reference-only class
    "Prism::CallTargetNode", // reference-only class
    "Prism::CapturePatternNode", // reference-only class
    "Prism::CaseMatchNode", // reference-only class
    "Prism::CaseNode", // reference-only class
    "Prism::ClassNode", // reference-only class
    "Prism::ClassVariableAndWriteNode", // reference-only class
    "Prism::ClassVariableOperatorWriteNode", // reference-only class
    "Prism::ClassVariableOrWriteNode", // reference-only class
    "Prism::ClassVariableReadNode", // reference-only class
    "Prism::ClassVariableTargetNode", // reference-only class
    "Prism::ClassVariableWriteNode", // reference-only class
    "Prism::CodeUnitsCache", // reference-only class
    "Prism::Comment", // reference-only class
    "Prism::Compiler", // reference-only class
    "Prism::ConstantAndWriteNode", // reference-only class
    "Prism::ConstantOperatorWriteNode", // reference-only class
    "Prism::ConstantOrWriteNode", // reference-only class
    "Prism::ConstantPathAndWriteNode", // reference-only class
    "Prism::ConstantPathNode", // reference-only class
    "Prism::ConstantPathNode::DynamicPartsInConstantPathError", // reference-only class
    "Prism::ConstantPathNode::MissingNodesInConstantPathError", // reference-only class
    "Prism::ConstantPathOperatorWriteNode", // reference-only class
    "Prism::ConstantPathOrWriteNode", // reference-only class
    "Prism::ConstantPathTargetNode", // reference-only class
    "Prism::ConstantPathWriteNode", // reference-only class
    "Prism::ConstantReadNode", // reference-only class
    "Prism::ConstantTargetNode", // reference-only class
    "Prism::ConstantWriteNode", // reference-only class
    "Prism::CurrentVersionError", // reference-only class
    "Prism::DSL", // reference-only module
    "Prism::DefNode", // reference-only class
    "Prism::DefinedNode", // reference-only class
    "Prism::Dispatcher", // reference-only class
    "Prism::Dispatcher::DispatchOnce", // reference-only class
    "Prism::DotVisitor", // reference-only class
    "Prism::ElseNode", // reference-only class
    "Prism::EmbDocComment", // reference-only class
    "Prism::EmbeddedStatementsNode", // reference-only class
    "Prism::EmbeddedVariableNode", // reference-only class
    "Prism::EncodingFlags", // reference-only module
    "Prism::EncodingFlags::FORCED_BINARY_ENCODING", // constant on the reference only
    "Prism::EncodingFlags::FORCED_UTF8_ENCODING", // constant on the reference only
    "Prism::EnsureNode", // reference-only class
    "Prism::FalseNode", // reference-only class
    "Prism::FindPatternNode", // reference-only class
    "Prism::FlipFlopNode", // reference-only class
    "Prism::FloatNode", // reference-only class
    "Prism::ForNode", // reference-only class
    "Prism::ForwardingArgumentsNode", // reference-only class
    "Prism::ForwardingParameterNode", // reference-only class
    "Prism::ForwardingSuperNode", // reference-only class
    "Prism::GlobalVariableAndWriteNode", // reference-only class
    "Prism::GlobalVariableOperatorWriteNode", // reference-only class
    "Prism::GlobalVariableOrWriteNode", // reference-only class
    "Prism::GlobalVariableReadNode", // reference-only class
    "Prism::GlobalVariableTargetNode", // reference-only class
    "Prism::GlobalVariableWriteNode", // reference-only class
    "Prism::HashNode", // reference-only class
    "Prism::HashPatternNode", // reference-only class
    "Prism::IfNode", // reference-only class
    "Prism::ImaginaryNode", // reference-only class
    "Prism::ImplicitNode", // reference-only class
    "Prism::ImplicitRestNode", // reference-only class
    "Prism::InNode", // reference-only class
    "Prism::IndexAndWriteNode", // reference-only class
    "Prism::IndexOperatorWriteNode", // reference-only class
    "Prism::IndexOrWriteNode", // reference-only class
    "Prism::IndexTargetNode", // reference-only class
    "Prism::InlineComment", // reference-only class
    "Prism::InspectVisitor", // reference-only class
    "Prism::InspectVisitor::Replace", // reference-only class
    "Prism::InstanceVariableAndWriteNode", // reference-only class
    "Prism::InstanceVariableOperatorWriteNode", // reference-only class
    "Prism::InstanceVariableOrWriteNode", // reference-only class
    "Prism::InstanceVariableReadNode", // reference-only class
    "Prism::InstanceVariableTargetNode", // reference-only class
    "Prism::InstanceVariableWriteNode", // reference-only class
    "Prism::IntegerBaseFlags", // reference-only module
    "Prism::IntegerBaseFlags::BINARY", // constant on the reference only
    "Prism::IntegerBaseFlags::DECIMAL", // constant on the reference only
    "Prism::IntegerBaseFlags::HEXADECIMAL", // constant on the reference only
    "Prism::IntegerBaseFlags::OCTAL", // constant on the reference only
    "Prism::IntegerNode", // reference-only class
    "Prism::InterpolatedMatchLastLineNode", // reference-only class
    "Prism::InterpolatedRegularExpressionNode", // reference-only class
    "Prism::InterpolatedStringNode", // reference-only class
    "Prism::InterpolatedStringNodeFlags", // reference-only module
    "Prism::InterpolatedStringNodeFlags::FROZEN", // constant on the reference only
    "Prism::InterpolatedStringNodeFlags::MUTABLE", // constant on the reference only
    "Prism::InterpolatedSymbolNode", // reference-only class
    "Prism::InterpolatedXStringNode", // reference-only class
    "Prism::ItLocalVariableReadNode", // reference-only class
    "Prism::ItParametersNode", // reference-only class
    "Prism::KeywordHashNode", // reference-only class
    "Prism::KeywordHashNodeFlags", // reference-only module
    "Prism::KeywordHashNodeFlags::SYMBOL_KEYS", // constant on the reference only
    "Prism::KeywordRestParameterNode", // reference-only class
    "Prism::LambdaNode", // reference-only class
    "Prism::LexCompat", // reference-only class
    "Prism::LexCompat::Result", // reference-only class
    "Prism::LexResult", // reference-only class
    "Prism::LocalVariableAndWriteNode", // reference-only class
    "Prism::LocalVariableOperatorWriteNode", // reference-only class
    "Prism::LocalVariableOrWriteNode", // reference-only class
    "Prism::LocalVariableReadNode", // reference-only class
    "Prism::LocalVariableTargetNode", // reference-only class
    "Prism::LocalVariableWriteNode", // reference-only class
    "Prism::Location", // reference-only class
    "Prism::LoopFlags", // reference-only module
    "Prism::LoopFlags::BEGIN_MODIFIER", // constant on the reference only
    "Prism::MagicComment", // reference-only class
    "Prism::MatchLastLineNode", // reference-only class
    "Prism::MatchPredicateNode", // reference-only class
    "Prism::MatchRequiredNode", // reference-only class
    "Prism::MatchWriteNode", // reference-only class
    "Prism::MissingNode", // reference-only class
    "Prism::ModuleNode", // reference-only class
    "Prism::MultiTargetNode", // reference-only class
    "Prism::MultiWriteNode", // reference-only class
    "Prism::MutationCompiler", // reference-only class
    "Prism::NextNode", // reference-only class
    "Prism::NilNode", // reference-only class
    "Prism::NoKeywordsParameterNode", // reference-only class
    "Prism::Node", // reference-only class
    "Prism::NodeFlags", // reference-only module
    "Prism::NodeFlags::NEWLINE", // constant on the reference only
    "Prism::NodeFlags::STATIC_LITERAL", // constant on the reference only
    "Prism::NumberedParametersNode", // reference-only class
    "Prism::NumberedReferenceReadNode", // reference-only class
    "Prism::OptionalKeywordParameterNode", // reference-only class
    "Prism::OptionalParameterNode", // reference-only class
    "Prism::OrNode", // reference-only class
    "Prism::Pack", // reference-only module
    "Prism::Pack::Directive", // reference-only class
    "Prism::Pack::Directive::directive_type", // type alias on the reference only
    "Prism::Pack::Directive::endianness", // type alias on the reference only
    "Prism::Pack::Directive::length_type", // type alias on the reference only
    "Prism::Pack::Directive::signness", // type alias on the reference only
    "Prism::Pack::Directive::size", // type alias on the reference only
    "Prism::Pack::Format", // reference-only class
    "Prism::Pack::variant", // type alias on the reference only
    "Prism::ParameterFlags", // reference-only module
    "Prism::ParameterFlags::REPEATED_PARAMETER", // constant on the reference only
    "Prism::ParametersNode", // reference-only class
    "Prism::ParenthesesNode", // reference-only class
    "Prism::ParenthesesNodeFlags", // reference-only module
    "Prism::ParenthesesNodeFlags::MULTIPLE_STATEMENTS", // constant on the reference only
    "Prism::ParseError", // reference-only class
    "Prism::ParseLexResult", // reference-only class
    "Prism::ParseResult", // reference-only class
    "Prism::ParseResult::Comments", // reference-only class
    "Prism::ParseResult::Comments::LocationTarget", // reference-only class
    "Prism::ParseResult::Comments::NodeTarget", // reference-only class
    "Prism::ParseResult::Comments::_Target", // reference-only interface
    "Prism::ParseWarning", // reference-only class
    "Prism::Pattern", // reference-only class
    "Prism::Pattern::CompilationError", // reference-only class
    "Prism::PinnedExpressionNode", // reference-only class
    "Prism::PinnedVariableNode", // reference-only class
    "Prism::PostExecutionNode", // reference-only class
    "Prism::PreExecutionNode", // reference-only class
    "Prism::ProgramNode", // reference-only class
    "Prism::RangeFlags", // reference-only module
    "Prism::RangeFlags::EXCLUDE_END", // constant on the reference only
    "Prism::RangeNode", // reference-only class
    "Prism::RationalNode", // reference-only class
    "Prism::RedoNode", // reference-only class
    "Prism::Reflection", // reference-only module
    "Prism::Reflection::ConstantField", // reference-only class
    "Prism::Reflection::ConstantListField", // reference-only class
    "Prism::Reflection::Field", // reference-only class
    "Prism::Reflection::FlagsField", // reference-only class
    "Prism::Reflection::FloatField", // reference-only class
    "Prism::Reflection::IntegerField", // reference-only class
    "Prism::Reflection::LocationField", // reference-only class
    "Prism::Reflection::NodeField", // reference-only class
    "Prism::Reflection::NodeListField", // reference-only class
    "Prism::Reflection::OptionalConstantField", // reference-only class
    "Prism::Reflection::OptionalLocationField", // reference-only class
    "Prism::Reflection::OptionalNodeField", // reference-only class
    "Prism::Reflection::StringField", // reference-only class
    "Prism::RegularExpressionFlags", // reference-only module
    "Prism::RegularExpressionFlags::ASCII_8BIT", // constant on the reference only
    "Prism::RegularExpressionFlags::EUC_JP", // constant on the reference only
    "Prism::RegularExpressionFlags::EXTENDED", // constant on the reference only
    "Prism::RegularExpressionFlags::FORCED_BINARY_ENCODING", // constant on the reference only
    "Prism::RegularExpressionFlags::FORCED_US_ASCII_ENCODING", // constant on the reference only
    "Prism::RegularExpressionFlags::FORCED_UTF8_ENCODING", // constant on the reference only
    "Prism::RegularExpressionFlags::IGNORE_CASE", // constant on the reference only
    "Prism::RegularExpressionFlags::MULTI_LINE", // constant on the reference only
    "Prism::RegularExpressionFlags::ONCE", // constant on the reference only
    "Prism::RegularExpressionFlags::UTF_8", // constant on the reference only
    "Prism::RegularExpressionFlags::WINDOWS_31J", // constant on the reference only
    "Prism::RegularExpressionNode", // reference-only class
    "Prism::Relocation", // reference-only module
    "Prism::Relocation::CharacterColumnsField", // reference-only class
    "Prism::Relocation::CharacterOffsetsField", // reference-only class
    "Prism::Relocation::CodeUnitColumnsField", // reference-only class
    "Prism::Relocation::CodeUnitOffsetsField", // reference-only class
    "Prism::Relocation::ColumnsField", // reference-only class
    "Prism::Relocation::CommentsField", // reference-only class
    "Prism::Relocation::CommentsField::Comment", // reference-only class
    "Prism::Relocation::Entry", // reference-only class
    "Prism::Relocation::Entry::MissingValueError", // reference-only class
    "Prism::Relocation::FilepathField", // reference-only class
    "Prism::Relocation::LeadingCommentsField", // reference-only class
    "Prism::Relocation::LinesField", // reference-only class
    "Prism::Relocation::OffsetsField", // reference-only class
    "Prism::Relocation::Repository", // reference-only class
    "Prism::Relocation::Repository::ConfigurationError", // reference-only class
    "Prism::Relocation::Source", // reference-only class
    "Prism::Relocation::SourceFilepath", // reference-only class
    "Prism::Relocation::SourceString", // reference-only class
    "Prism::Relocation::TrailingCommentsField", // reference-only class
    "Prism::Relocation::_Field", // reference-only interface
    "Prism::Relocation::_Value", // reference-only interface
    "Prism::Relocation::entry_value", // type alias on the reference only
    "Prism::Relocation::entry_values", // type alias on the reference only
    "Prism::RequiredKeywordParameterNode", // reference-only class
    "Prism::RequiredParameterNode", // reference-only class
    "Prism::RescueModifierNode", // reference-only class
    "Prism::RescueNode", // reference-only class
    "Prism::RestParameterNode", // reference-only class
    "Prism::Result", // reference-only class
    "Prism::RetryNode", // reference-only class
    "Prism::ReturnNode", // reference-only class
    "Prism::Scope", // reference-only class
    "Prism::SelfNode", // reference-only class
    "Prism::Serialize", // reference-only module
    "Prism::ShareableConstantNode", // reference-only class
    "Prism::ShareableConstantNodeFlags", // reference-only module
    "Prism::ShareableConstantNodeFlags::EXPERIMENTAL_COPY", // constant on the reference only
    "Prism::ShareableConstantNodeFlags::EXPERIMENTAL_EVERYTHING", // constant on the reference only
    "Prism::ShareableConstantNodeFlags::LITERAL", // constant on the reference only
    "Prism::SingletonClassNode", // reference-only class
    "Prism::Source", // reference-only class
    "Prism::SourceEncodingNode", // reference-only class
    "Prism::SourceFileNode", // reference-only class
    "Prism::SourceLineNode", // reference-only class
    "Prism::SplatNode", // reference-only class
    "Prism::StatementsNode", // reference-only class
    "Prism::StringFlags", // reference-only module
    "Prism::StringFlags::FORCED_BINARY_ENCODING", // constant on the reference only
    "Prism::StringFlags::FORCED_UTF8_ENCODING", // constant on the reference only
    "Prism::StringFlags::FROZEN", // constant on the reference only
    "Prism::StringFlags::MUTABLE", // constant on the reference only
    "Prism::StringNode", // reference-only class
    "Prism::StringQuery", // reference-only class
    "Prism::SuperNode", // reference-only class
    "Prism::SymbolFlags", // reference-only module
    "Prism::SymbolFlags::FORCED_BINARY_ENCODING", // constant on the reference only
    "Prism::SymbolFlags::FORCED_US_ASCII_ENCODING", // constant on the reference only
    "Prism::SymbolFlags::FORCED_UTF8_ENCODING", // constant on the reference only
    "Prism::SymbolNode", // reference-only class
    "Prism::Token", // reference-only class
    "Prism::TrueNode", // reference-only class
    "Prism::UndefNode", // reference-only class
    "Prism::UnlessNode", // reference-only class
    "Prism::UntilNode", // reference-only class
    "Prism::VERSION", // constant on the reference only
    "Prism::Visitor", // reference-only class
    "Prism::WhenNode", // reference-only class
    "Prism::WhileNode", // reference-only class
    "Prism::XStringNode", // reference-only class
    "Prism::YieldNode", // reference-only class
    "Prism::_CodeUnitsCache", // reference-only interface
    "Prism::_Comment", // reference-only interface
    "Prism::_Node", // reference-only interface
    "Prism::_Repository", // reference-only interface
    "Prism::_Stream", // reference-only interface
    "Prism::_Visitor", // reference-only interface
    "Prism::comment", // type alias on the reference only
    "Prism::node", // type alias on the reference only
    "RBS::AST", // reference-only module
    "RBS::AST::Annotation", // reference-only class
    "RBS::AST::Comment", // reference-only class
    "RBS::AST::Declarations", // reference-only module
    "RBS::AST::Declarations::AliasDecl", // reference-only class
    "RBS::AST::Declarations::AliasDecl::loc", // type alias on the reference only
    "RBS::AST::Declarations::Base", // reference-only class
    "RBS::AST::Declarations::Class", // reference-only class
    "RBS::AST::Declarations::Class::Super", // reference-only class
    "RBS::AST::Declarations::Class::Super::loc", // type alias on the reference only
    "RBS::AST::Declarations::Class::loc", // type alias on the reference only
    "RBS::AST::Declarations::Class::member", // type alias on the reference only
    "RBS::AST::Declarations::ClassAlias", // reference-only class
    "RBS::AST::Declarations::Constant", // reference-only class
    "RBS::AST::Declarations::Constant::loc", // type alias on the reference only
    "RBS::AST::Declarations::Global", // reference-only class
    "RBS::AST::Declarations::Global::loc", // type alias on the reference only
    "RBS::AST::Declarations::Interface", // reference-only class
    "RBS::AST::Declarations::Interface::loc", // type alias on the reference only
    "RBS::AST::Declarations::Interface::member", // type alias on the reference only
    "RBS::AST::Declarations::MixinHelper", // reference-only module
    "RBS::AST::Declarations::MixinHelper::mixin_member", // type alias on the reference only
    "RBS::AST::Declarations::Module", // reference-only class
    "RBS::AST::Declarations::Module::Self", // reference-only class
    "RBS::AST::Declarations::Module::Self::loc", // type alias on the reference only
    "RBS::AST::Declarations::Module::loc", // type alias on the reference only
    "RBS::AST::Declarations::Module::member", // type alias on the reference only
    "RBS::AST::Declarations::ModuleAlias", // reference-only class
    "RBS::AST::Declarations::NestedDeclarationHelper", // reference-only module
    "RBS::AST::Declarations::TypeAlias", // reference-only class
    "RBS::AST::Declarations::TypeAlias::loc", // type alias on the reference only
    "RBS::AST::Declarations::_WithMember", // reference-only interface
    "RBS::AST::Declarations::t", // type alias on the reference only
    "RBS::AST::Directives", // reference-only module
    "RBS::AST::Directives::Base", // reference-only class
    "RBS::AST::Directives::ResolveTypeNames", // reference-only class
    "RBS::AST::Directives::ResolveTypeNames::loc", // type alias on the reference only
    "RBS::AST::Directives::Use", // reference-only class
    "RBS::AST::Directives::Use::SingleClause", // reference-only class
    "RBS::AST::Directives::Use::SingleClause::loc", // type alias on the reference only
    "RBS::AST::Directives::Use::WildcardClause", // reference-only class
    "RBS::AST::Directives::Use::WildcardClause::loc", // type alias on the reference only
    "RBS::AST::Directives::Use::clause", // type alias on the reference only
    "RBS::AST::Directives::Use::loc", // type alias on the reference only
    "RBS::AST::Directives::t", // type alias on the reference only
    "RBS::AST::Members", // reference-only module
    "RBS::AST::Members::Alias", // reference-only class
    "RBS::AST::Members::Alias::kind", // type alias on the reference only
    "RBS::AST::Members::Alias::loc", // type alias on the reference only
    "RBS::AST::Members::AttrAccessor", // reference-only class
    "RBS::AST::Members::AttrReader", // reference-only class
    "RBS::AST::Members::AttrWriter", // reference-only class
    "RBS::AST::Members::Attribute", // reference-only module
    "RBS::AST::Members::Attribute::kind", // type alias on the reference only
    "RBS::AST::Members::Attribute::loc", // type alias on the reference only
    "RBS::AST::Members::Base", // reference-only class
    "RBS::AST::Members::ClassInstanceVariable", // reference-only class
    "RBS::AST::Members::ClassVariable", // reference-only class
    "RBS::AST::Members::Extend", // reference-only class
    "RBS::AST::Members::Include", // reference-only class
    "RBS::AST::Members::InstanceVariable", // reference-only class
    "RBS::AST::Members::LocationOnly", // reference-only module
    "RBS::AST::Members::MethodDefinition", // reference-only class
    "RBS::AST::Members::MethodDefinition::Overload", // reference-only class
    "RBS::AST::Members::MethodDefinition::kind", // type alias on the reference only
    "RBS::AST::Members::MethodDefinition::loc", // type alias on the reference only
    "RBS::AST::Members::Mixin", // reference-only module
    "RBS::AST::Members::Mixin::loc", // type alias on the reference only
    "RBS::AST::Members::Prepend", // reference-only class
    "RBS::AST::Members::Private", // reference-only class
    "RBS::AST::Members::Public", // reference-only class
    "RBS::AST::Members::Var", // reference-only module
    "RBS::AST::Members::Var::loc", // type alias on the reference only
    "RBS::AST::Members::t", // type alias on the reference only
    "RBS::AST::Members::visibility", // type alias on the reference only
    "RBS::AST::Ruby", // reference-only module
    "RBS::AST::Ruby::Annotations", // reference-only module
    "RBS::AST::Ruby::Annotations::AliasAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::Base", // reference-only class
    "RBS::AST::Ruby::Annotations::BlockParamTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::ClassAliasAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::ColonMethodTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::DoubleSplatParamTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::InstanceVariableAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::MethodTypesAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::MethodTypesAnnotation::Overload", // class alias on the reference only
    "RBS::AST::Ruby::Annotations::ModuleAliasAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::ModuleSelfAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::NodeTypeAssertion", // reference-only class
    "RBS::AST::Ruby::Annotations::ParamTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::ReturnTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::SkipAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::SplatParamTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::TypeApplicationAnnotation", // reference-only class
    "RBS::AST::Ruby::Annotations::leading_annotation", // type alias on the reference only
    "RBS::AST::Ruby::Annotations::t", // type alias on the reference only
    "RBS::AST::Ruby::Annotations::trailing_annotation", // type alias on the reference only
    "RBS::AST::Ruby::CommentBlock", // reference-only class
    "RBS::AST::Ruby::CommentBlock::AnnotationSyntaxError", // reference-only class
    "RBS::AST::Ruby::Declarations", // reference-only module
    "RBS::AST::Ruby::Declarations::Base", // reference-only class
    "RBS::AST::Ruby::Declarations::ClassDecl", // reference-only class
    "RBS::AST::Ruby::Declarations::ClassDecl::SuperClass", // reference-only class
    "RBS::AST::Ruby::Declarations::ClassDecl::member", // type alias on the reference only
    "RBS::AST::Ruby::Declarations::ClassModuleAliasDecl", // reference-only class
    "RBS::AST::Ruby::Declarations::ClassModuleAliasDecl::annotation", // type alias on the reference only
    "RBS::AST::Ruby::Declarations::ClassModuleAliasDecl::node", // type alias on the reference only
    "RBS::AST::Ruby::Declarations::ConstantDecl", // reference-only class
    "RBS::AST::Ruby::Declarations::ConstantDecl::node", // type alias on the reference only
    "RBS::AST::Ruby::Declarations::ModuleDecl", // reference-only class
    "RBS::AST::Ruby::Declarations::ModuleDecl::member", // type alias on the reference only
    "RBS::AST::Ruby::Declarations::t", // type alias on the reference only
    "RBS::AST::Ruby::Helpers", // reference-only module
    "RBS::AST::Ruby::Helpers::ConstantHelper", // reference-only module
    "RBS::AST::Ruby::Helpers::LocationHelper", // reference-only module
    "RBS::AST::Ruby::Helpers::LocationHelper::_WithBuffer", // reference-only interface
    "RBS::AST::Ruby::Members", // reference-only module
    "RBS::AST::Ruby::Members::AttrAccessorMember", // reference-only class
    "RBS::AST::Ruby::Members::AttrReaderMember", // reference-only class
    "RBS::AST::Ruby::Members::AttrWriterMember", // reference-only class
    "RBS::AST::Ruby::Members::AttributeMember", // reference-only class
    "RBS::AST::Ruby::Members::Base", // reference-only class
    "RBS::AST::Ruby::Members::DefMember", // reference-only class
    "RBS::AST::Ruby::Members::DefMember::Overload", // class alias on the reference only
    "RBS::AST::Ruby::Members::ExtendMember", // reference-only class
    "RBS::AST::Ruby::Members::IncludeMember", // reference-only class
    "RBS::AST::Ruby::Members::InstanceVariableMember", // reference-only class
    "RBS::AST::Ruby::Members::MethodTypeAnnotation", // reference-only class
    "RBS::AST::Ruby::Members::MethodTypeAnnotation::DocStyle", // reference-only class
    "RBS::AST::Ruby::Members::MethodTypeAnnotation::DocStyle::param_type_annotation", // type alias on the reference only
    "RBS::AST::Ruby::Members::MethodTypeAnnotation::type_annotations", // type alias on the reference only
    "RBS::AST::Ruby::Members::MixinMember", // reference-only class
    "RBS::AST::Ruby::Members::ModuleSelfMember", // reference-only class
    "RBS::AST::Ruby::Members::PrependMember", // reference-only class
    "RBS::AST::Ruby::Members::t", // type alias on the reference only
    "RBS::AST::TypeParam", // reference-only class
    "RBS::AST::TypeParam::bound", // type alias on the reference only
    "RBS::AST::TypeParam::loc", // type alias on the reference only
    "RBS::AST::TypeParam::variance", // type alias on the reference only
    "RBS::AST::Visitor", // reference-only class
    "RBS::AncestorGraph", // reference-only class
    "RBS::AncestorGraph::InstanceNode", // reference-only class
    "RBS::AncestorGraph::SingletonNode", // reference-only class
    "RBS::AncestorGraph::node", // type alias on the reference only
    "RBS::Annotate", // reference-only module
    "RBS::Annotate::Annotations", // reference-only class
    "RBS::Annotate::Annotations::Copy", // reference-only class
    "RBS::Annotate::Annotations::Skip", // reference-only class
    "RBS::Annotate::Annotations::Source", // reference-only class
    "RBS::Annotate::Annotations::t", // type alias on the reference only
    "RBS::Annotate::Formatter", // reference-only class
    "RBS::Annotate::RDocAnnotator", // reference-only class
    "RBS::Annotate::RDocAnnotator::_Annotated", // reference-only interface
    "RBS::Annotate::RDocAnnotator::_Commented", // reference-only interface
    "RBS::Annotate::RDocAnnotator::_PathTester", // reference-only interface
    "RBS::Annotate::RDocAnnotator::_WithRDocComment", // reference-only interface
    "RBS::Annotate::RDocSource", // reference-only class
    "RBS::BaseError", // reference-only class
    "RBS::Buffer", // reference-only class
    "RBS::Buffer::loc", // type alias on the reference only
    "RBS::BuiltinNames", // reference-only module
    "RBS::BuiltinNames::Array", // constant on the reference only
    "RBS::BuiltinNames::BasicObject", // constant on the reference only
    "RBS::BuiltinNames::Class", // constant on the reference only
    "RBS::BuiltinNames::Comparable", // constant on the reference only
    "RBS::BuiltinNames::Enumerable", // constant on the reference only
    "RBS::BuiltinNames::Enumerator", // constant on the reference only
    "RBS::BuiltinNames::FalseClass", // constant on the reference only
    "RBS::BuiltinNames::Float", // constant on the reference only
    "RBS::BuiltinNames::Hash", // constant on the reference only
    "RBS::BuiltinNames::Integer", // constant on the reference only
    "RBS::BuiltinNames::Kernel", // constant on the reference only
    "RBS::BuiltinNames::Module", // constant on the reference only
    "RBS::BuiltinNames::Name", // reference-only class
    "RBS::BuiltinNames::Numeric", // constant on the reference only
    "RBS::BuiltinNames::Object", // constant on the reference only
    "RBS::BuiltinNames::Range", // constant on the reference only
    "RBS::BuiltinNames::Regexp", // constant on the reference only
    "RBS::BuiltinNames::Set", // constant on the reference only
    "RBS::BuiltinNames::String", // constant on the reference only
    "RBS::BuiltinNames::Symbol", // constant on the reference only
    "RBS::BuiltinNames::TrueClass", // constant on the reference only
    "RBS::CLI", // reference-only class
    "RBS::CLI::COMMANDS", // constant on the reference only
    "RBS::CLI::ColoredIO", // reference-only class
    "RBS::CLI::Diff", // reference-only class
    "RBS::CLI::LibraryOptions", // reference-only class
    "RBS::CLI::Validate", // reference-only class
    "RBS::CLI::Validate::Errors", // reference-only class
    "RBS::CLI::_IO", // reference-only interface
    "RBS::ClassInstanceVariableDuplicationError", // reference-only class
    "RBS::Collection", // reference-only module
    "RBS::Collection::Cleaner", // reference-only class
    "RBS::Collection::Config", // reference-only class
    "RBS::Collection::Config::CollectionNotAvailable", // reference-only class
    "RBS::Collection::Config::Lockfile", // reference-only class
    "RBS::Collection::Config::Lockfile::library", // type alias on the reference only
    "RBS::Collection::Config::Lockfile::library_data", // type alias on the reference only
    "RBS::Collection::Config::Lockfile::lockfile_data", // type alias on the reference only
    "RBS::Collection::Config::LockfileGenerator", // reference-only class
    "RBS::Collection::Config::LockfileGenerator::ALUMNI_STDLIBS", // constant on the reference only
    "RBS::Collection::Config::LockfileGenerator::GemfileLockMismatchError", // reference-only class
    "RBS::Collection::Config::LockfileGenerator::NONGEM_STDLIBS", // constant on the reference only
    "RBS::Collection::Config::PATH", // constant on the reference only
    "RBS::Collection::Config::gem_entry", // type alias on the reference only
    "RBS::Collection::Installer", // reference-only class
    "RBS::Collection::Sources", // reference-only module
    "RBS::Collection::Sources::Base", // reference-only module
    "RBS::Collection::Sources::Git", // reference-only class
    "RBS::Collection::Sources::Git::CommandError", // reference-only class
    "RBS::Collection::Sources::Git::METADATA_FILENAME", // constant on the reference only
    "RBS::Collection::Sources::Git::metadata", // type alias on the reference only
    "RBS::Collection::Sources::Git::source_entry", // type alias on the reference only
    "RBS::Collection::Sources::Local", // reference-only class
    "RBS::Collection::Sources::Local::source_entry", // type alias on the reference only
    "RBS::Collection::Sources::Rubygems", // reference-only class
    "RBS::Collection::Sources::Rubygems::source_entry", // type alias on the reference only
    "RBS::Collection::Sources::Stdlib", // reference-only class
    "RBS::Collection::Sources::Stdlib::REPO", // constant on the reference only
    "RBS::Collection::Sources::Stdlib::source_entry", // type alias on the reference only
    "RBS::Collection::Sources::_Source", // reference-only interface
    "RBS::Collection::Sources::manifest_dependency", // type alias on the reference only
    "RBS::Collection::Sources::manifest_entry", // type alias on the reference only
    "RBS::Collection::Sources::source_entry", // type alias on the reference only
    "RBS::Collection::Sources::t", // type alias on the reference only
    "RBS::Constant", // reference-only class
    "RBS::Constant::constant_entry", // type alias on the reference only
    "RBS::CyclicClassAliasDefinitionError", // reference-only class
    "RBS::CyclicTypeParameterBound", // reference-only class
    "RBS::Definition", // reference-only class
    "RBS::Definition::Ancestor", // reference-only module
    "RBS::Definition::Ancestor::Instance", // reference-only class
    "RBS::Definition::Ancestor::Instance::source", // type alias on the reference only
    "RBS::Definition::Ancestor::Singleton", // reference-only class
    "RBS::Definition::Ancestor::t", // type alias on the reference only
    "RBS::Definition::InstanceAncestors", // reference-only class
    "RBS::Definition::Method", // reference-only class
    "RBS::Definition::Method::TypeDef", // reference-only class
    "RBS::Definition::Method::method_member", // type alias on the reference only
    "RBS::Definition::SingletonAncestors", // reference-only class
    "RBS::Definition::Variable", // reference-only class
    "RBS::Definition::Variable::source", // type alias on the reference only
    "RBS::Definition::accessibility", // type alias on the reference only
    "RBS::Definition::definition_entry", // type alias on the reference only
    "RBS::Definition::self_type", // type alias on the reference only
    "RBS::DefinitionBuilder", // reference-only class
    "RBS::DefinitionBuilder::AncestorBuilder", // reference-only class
    "RBS::DefinitionBuilder::AncestorBuilder::OneAncestors", // reference-only class
    "RBS::DefinitionBuilder::MethodBuilder", // reference-only class
    "RBS::DefinitionBuilder::MethodBuilder::Methods", // reference-only class
    "RBS::DefinitionBuilder::MethodBuilder::Methods::Definition", // reference-only class
    "RBS::DefinitionBuilder::MethodBuilder::Methods::Definition::accessibility", // type alias on the reference only
    "RBS::DefinitionBuilder::MethodBuilder::Methods::Definition::original", // type alias on the reference only
    "RBS::DefinitionBuilder::MethodBuilder::Methods::Definition::overloading_definition", // type alias on the reference only
    "RBS::DefinitionBuilder::MethodBuilder::Methods::Sorter", // reference-only class
    "RBS::DefinitionBuilder::MethodBuilder::Methods::instance_type", // type alias on the reference only
    "RBS::DefinitionBuilder::interface_methods", // type alias on the reference only
    "RBS::DefinitionError", // reference-only class
    "RBS::DetailedMessageable", // reference-only module
    "RBS::Diff", // reference-only class
    "RBS::DuplicatedDeclarationError", // reference-only class
    "RBS::DuplicatedDeclarationError::declaration", // type alias on the reference only
    "RBS::DuplicatedInterfaceMethodDefinitionError", // reference-only class
    "RBS::DuplicatedInterfaceMethodDefinitionError::mixin_member", // type alias on the reference only
    "RBS::DuplicatedInterfaceMethodDefinitionError::ty", // type alias on the reference only
    "RBS::DuplicatedMethodDefinitionError", // reference-only class
    "RBS::DuplicatedMethodDefinitionError::original", // type alias on the reference only
    "RBS::DuplicatedMethodDefinitionError::ty", // type alias on the reference only
    "RBS::Environment", // reference-only class
    "RBS::Environment::ClassAliasEntry", // reference-only class
    "RBS::Environment::ClassEntry", // reference-only class
    "RBS::Environment::ClassEntry::context_decl", // type alias on the reference only
    "RBS::Environment::ClassEntry::declaration", // type alias on the reference only
    "RBS::Environment::ConstantEntry", // reference-only class
    "RBS::Environment::GlobalEntry", // reference-only class
    "RBS::Environment::InterfaceEntry", // reference-only class
    "RBS::Environment::ModuleAliasEntry", // reference-only class
    "RBS::Environment::ModuleEntry", // reference-only class
    "RBS::Environment::ModuleEntry::context_decl", // type alias on the reference only
    "RBS::Environment::ModuleEntry::declaration", // type alias on the reference only
    "RBS::Environment::SingleEntry", // reference-only class
    "RBS::Environment::TypeAliasEntry", // reference-only class
    "RBS::Environment::UseMap", // reference-only class
    "RBS::Environment::UseMap::Table", // reference-only class
    "RBS::Environment::module_decl", // type alias on the reference only
    "RBS::EnvironmentLoader", // reference-only class
    "RBS::EnvironmentLoader::DEFAULT_CORE_ROOT", // constant on the reference only
    "RBS::EnvironmentLoader::Library", // reference-only class
    "RBS::EnvironmentLoader::UnknownLibraryError", // reference-only class
    "RBS::EnvironmentLoader::source", // type alias on the reference only
    "RBS::EnvironmentWalker", // reference-only class
    "RBS::EnvironmentWalker::InstanceNode", // reference-only class
    "RBS::EnvironmentWalker::SingletonNode", // reference-only class
    "RBS::EnvironmentWalker::TypeNameNode", // reference-only class
    "RBS::EnvironmentWalker::node", // type alias on the reference only
    "RBS::Factory", // reference-only class
    "RBS::FileFinder", // reference-only module
    "RBS::GenericParameterMismatchError", // reference-only class
    "RBS::GenericParameterMismatchError::decl", // type alias on the reference only
    "RBS::InconsistentClassModuleAliasError", // reference-only class
    "RBS::InheritModuleError", // reference-only class
    "RBS::InheritModuleError::super_class", // type alias on the reference only
    "RBS::InlineParser", // reference-only class
    "RBS::InlineParser::CommentAssociation", // reference-only class
    "RBS::InlineParser::CommentAssociation::Reference", // reference-only class
    "RBS::InlineParser::Diagnostic", // reference-only module
    "RBS::InlineParser::Diagnostic::AnnotationSyntaxError", // reference-only class
    "RBS::InlineParser::Diagnostic::AttributeNonSymbolName", // reference-only class
    "RBS::InlineParser::Diagnostic::Base", // reference-only class
    "RBS::InlineParser::Diagnostic::ClassModuleAliasDeclarationMissingTypeName", // reference-only class
    "RBS::InlineParser::Diagnostic::MixinMultipleArguments", // reference-only class
    "RBS::InlineParser::Diagnostic::MixinNonConstantModule", // reference-only class
    "RBS::InlineParser::Diagnostic::NonConstantClassName", // reference-only class
    "RBS::InlineParser::Diagnostic::NonConstantConstantDeclaration", // reference-only class
    "RBS::InlineParser::Diagnostic::NonConstantModuleName", // reference-only class
    "RBS::InlineParser::Diagnostic::NonConstantSuperClassName", // reference-only class
    "RBS::InlineParser::Diagnostic::NotImplementedYet", // reference-only class
    "RBS::InlineParser::Diagnostic::TopLevelAttributeDefinition", // reference-only class
    "RBS::InlineParser::Diagnostic::TopLevelMethodDefinition", // reference-only class
    "RBS::InlineParser::Diagnostic::UnusedInlineAnnotation", // reference-only class
    "RBS::InlineParser::Diagnostic::t", // type alias on the reference only
    "RBS::InlineParser::Parser", // reference-only class
    "RBS::InlineParser::Parser::module_context", // type alias on the reference only
    "RBS::InlineParser::Result", // reference-only class
    "RBS::InstanceVariableDuplicationError", // reference-only class
    "RBS::InvalidOverloadMethodError", // reference-only class
    "RBS::InvalidOverloadMethodError::member", // type alias on the reference only
    "RBS::InvalidTypeApplicationError", // reference-only class
    "RBS::InvalidVarianceAnnotationError", // reference-only class
    "RBS::LoadingError", // reference-only class
    "RBS::Location", // reference-only class
    "RBS::Location::WithChildren", // constant on the reference only
    "RBS::Locator", // reference-only class
    "RBS::Locator::component", // type alias on the reference only
    "RBS::MethodNameHelper", // reference-only module
    "RBS::MethodType", // reference-only class
    "RBS::MethodType::attr_loc", // type alias on the reference only
    "RBS::MethodType::def_loc", // type alias on the reference only
    "RBS::MethodType::loc", // type alias on the reference only
    "RBS::MixinClassError", // reference-only class
    "RBS::MixinClassError::member", // type alias on the reference only
    "RBS::Namespace", // reference-only class
    "RBS::Namespace::INTERN_LEAF", // constant on the reference only
    "RBS::NoMixinFoundError", // reference-only class
    "RBS::NoMixinFoundError::member", // type alias on the reference only
    "RBS::NoSelfTypeFoundError", // reference-only class
    "RBS::NoSuperclassFoundError", // reference-only class
    "RBS::NoTypeFoundError", // reference-only class
    "RBS::NonregularTypeAliasError", // reference-only class
    "RBS::Parser", // reference-only class
    "RBS::Parser::KEYWORDS", // constant on the reference only
    "RBS::Parser::LexResult", // reference-only class
    "RBS::Parser::LexerError", // constant on the reference only
    "RBS::Parser::LocatedValue", // reference-only class
    "RBS::Parser::SemanticsError", // constant on the reference only
    "RBS::Parser::SyntaxError", // constant on the reference only
    "RBS::Parser::Token", // reference-only class
    "RBS::ParsingError", // reference-only class
    "RBS::Prototype", // reference-only module
    "RBS::Prototype::Helpers", // reference-only module
    "RBS::Prototype::Helpers::node", // type alias on the reference only
    "RBS::Prototype::NodeUsage", // reference-only class
    "RBS::Prototype::NodeUsage::node", // type alias on the reference only
    "RBS::Prototype::RB", // reference-only class
    "RBS::Prototype::RB::Context", // reference-only class
    "RBS::Prototype::RB::Context::method_kind", // type alias on the reference only
    "RBS::Prototype::RB::decl", // type alias on the reference only
    "RBS::Prototype::RBI", // reference-only class
    "RBS::Prototype::RBI::Context", // reference-only class
    "RBS::Prototype::RBI::module_decl", // type alias on the reference only
    "RBS::Prototype::RBI::visibility", // type alias on the reference only
    "RBS::Prototype::Runtime", // reference-only class
    "RBS::Prototype::Runtime::DataGenerator", // reference-only class
    "RBS::Prototype::Runtime::Helpers", // reference-only module
    "RBS::Prototype::Runtime::Reflection", // reference-only module
    "RBS::Prototype::Runtime::StructGenerator", // reference-only class
    "RBS::Prototype::Runtime::StructGenerator::CAN_CALL_KEYWORD_INIT_P", // constant on the reference only
    "RBS::Prototype::Runtime::Todo", // reference-only class
    "RBS::Prototype::Runtime::ValueObjectBase", // reference-only class
    "RBS::Prototype::Runtime::mixin_class", // type alias on the reference only
    "RBS::RDocPlugin", // reference-only module
    "RBS::RDocPlugin::Parser", // reference-only class
    "RBS::RDocPlugin::Parser::_DeclWithComment", // reference-only interface
    "RBS::RDocPlugin::Parser::allowed_decls", // type alias on the reference only
    "RBS::RecursiveAliasDefinitionError", // reference-only class
    "RBS::RecursiveAliasDefinitionError::defn", // type alias on the reference only
    "RBS::RecursiveAliasDefinitionError::ty", // type alias on the reference only
    "RBS::RecursiveAncestorError", // reference-only class
    "RBS::RecursiveTypeAliasError", // reference-only class
    "RBS::Repository", // reference-only class
    "RBS::Repository::DEFAULT_STDLIB_ROOT", // constant on the reference only
    "RBS::Repository::GemRBS", // reference-only class
    "RBS::Repository::VersionPath", // reference-only class
    "RBS::Resolver", // reference-only module
    "RBS::Resolver::ConstantResolver", // reference-only class
    "RBS::Resolver::ConstantResolver::Table", // reference-only class
    "RBS::Resolver::TypeNameResolver", // reference-only class
    "RBS::Resolver::context", // type alias on the reference only
    "RBS::Rewriter", // reference-only class
    "RBS::Sorter", // reference-only class
    "RBS::Sorter::member", // type alias on the reference only
    "RBS::Sorter::partitioned", // type alias on the reference only
    "RBS::Source", // reference-only module
    "RBS::Source::RBS", // reference-only class
    "RBS::Source::Ruby", // reference-only class
    "RBS::Source::t", // type alias on the reference only
    "RBS::Substitution", // reference-only class
    "RBS::Subtractor", // reference-only class
    "RBS::Subtractor::decl_with_members", // type alias on the reference only
    "RBS::SuperclassMismatchError", // reference-only class
    "RBS::Test", // reference-only module
    "RBS::Test::ArgumentsReturn", // reference-only class
    "RBS::Test::ArgumentsReturn::exit_type", // type alias on the reference only
    "RBS::Test::CLASS", // constant on the reference only
    "RBS::Test::CallTrace", // reference-only class
    "RBS::Test::DEFINE_METHOD", // constant on the reference only
    "RBS::Test::Errors", // reference-only module
    "RBS::Test::Errors::ArgumentError", // reference-only class
    "RBS::Test::Errors::ArgumentTypeError", // reference-only class
    "RBS::Test::Errors::BlockArgumentError", // reference-only class
    "RBS::Test::Errors::BlockArgumentTypeError", // reference-only class
    "RBS::Test::Errors::BlockReturnTypeError", // reference-only class
    "RBS::Test::Errors::MissingBlockError", // reference-only class
    "RBS::Test::Errors::RESPOND_TO", // constant on the reference only
    "RBS::Test::Errors::ReturnTypeError", // reference-only class
    "RBS::Test::Errors::UnexpectedBlockError", // reference-only class
    "RBS::Test::Errors::UnresolvedOverloadingError", // reference-only class
    "RBS::Test::Errors::t", // type alias on the reference only
    "RBS::Test::Guaranteed", // reference-only module
    "RBS::Test::Guaranteed::Inspect", // reference-only module
    "RBS::Test::INSPECT", // constant on the reference only
    "RBS::Test::INSTANCE_EVAL", // constant on the reference only
    "RBS::Test::INSTANCE_EXEC", // constant on the reference only
    "RBS::Test::IS_AP", // constant on the reference only
    "RBS::Test::METHOD", // constant on the reference only
    "RBS::Test::METHODS", // constant on the reference only
    "RBS::Test::PP", // constant on the reference only
    "RBS::Test::RESPOND_TOP", // constant on the reference only
    "RBS::Test::SINGLETON_CLASS", // constant on the reference only
    "RBS::Test::TypeCheck", // reference-only class
    "RBS::TypeAliasDependency", // reference-only class
    "RBS::TypeAliasRegularity", // reference-only class
    "RBS::TypeAliasRegularity::Diagnostic", // reference-only class
    "RBS::TypeName", // reference-only class
    "RBS::TypeName::kind", // type alias on the reference only
    "RBS::TypeParamDefaultReferenceError", // reference-only class
    "RBS::Types", // reference-only module
    "RBS::Types::Alias", // reference-only class
    "RBS::Types::Alias::loc", // type alias on the reference only
    "RBS::Types::Application", // reference-only module
    "RBS::Types::Bases", // reference-only module
    "RBS::Types::Bases::Any", // reference-only class
    "RBS::Types::Bases::Base", // reference-only class
    "RBS::Types::Bases::Bool", // reference-only class
    "RBS::Types::Bases::Bottom", // reference-only class
    "RBS::Types::Bases::Class", // reference-only class
    "RBS::Types::Bases::Instance", // reference-only class
    "RBS::Types::Bases::Nil", // reference-only class
    "RBS::Types::Bases::Self", // reference-only class
    "RBS::Types::Bases::Top", // reference-only class
    "RBS::Types::Bases::Void", // reference-only class
    "RBS::Types::Block", // reference-only class
    "RBS::Types::Block::loc", // type alias on the reference only
    "RBS::Types::ClassInstance", // reference-only class
    "RBS::Types::ClassInstance::loc", // type alias on the reference only
    "RBS::Types::ClassSingleton", // reference-only class
    "RBS::Types::ClassSingleton::loc", // type alias on the reference only
    "RBS::Types::EmptyEachType", // reference-only module
    "RBS::Types::Function", // reference-only class
    "RBS::Types::Function::ForwardingParam", // reference-only class
    "RBS::Types::Function::Param", // reference-only class
    "RBS::Types::Function::Param::loc", // type alias on the reference only
    "RBS::Types::Interface", // reference-only class
    "RBS::Types::Interface::loc", // type alias on the reference only
    "RBS::Types::Intersection", // reference-only class
    "RBS::Types::Intersection::loc", // type alias on the reference only
    "RBS::Types::Literal", // reference-only class
    "RBS::Types::Literal::TABLE", // constant on the reference only
    "RBS::Types::Literal::literal", // type alias on the reference only
    "RBS::Types::Literal::loc", // type alias on the reference only
    "RBS::Types::NoFreeVariables", // reference-only module
    "RBS::Types::NoSubst", // reference-only module
    "RBS::Types::NoTypeName", // reference-only module
    "RBS::Types::Optional", // reference-only class
    "RBS::Types::Optional::loc", // type alias on the reference only
    "RBS::Types::Proc", // reference-only class
    "RBS::Types::Proc::loc", // type alias on the reference only
    "RBS::Types::Record", // reference-only class
    "RBS::Types::Record::key", // type alias on the reference only
    "RBS::Types::Record::loc", // type alias on the reference only
    "RBS::Types::SelfTypeBindingHelper", // reference-only module
    "RBS::Types::Tuple", // reference-only class
    "RBS::Types::Tuple::loc", // type alias on the reference only
    "RBS::Types::Union", // reference-only class
    "RBS::Types::Union::loc", // type alias on the reference only
    "RBS::Types::UntypedFunction", // reference-only class
    "RBS::Types::Variable", // reference-only class
    "RBS::Types::Variable::loc", // type alias on the reference only
    "RBS::Types::_TypeBase", // reference-only interface
    "RBS::Types::function", // type alias on the reference only
    "RBS::Types::t", // type alias on the reference only
    "RBS::UnitTest", // reference-only module
    "RBS::UnitTest::Convertibles", // reference-only module
    "RBS::UnitTest::Convertibles::BlankSlate", // reference-only class
    "RBS::UnitTest::Convertibles::CustomRange", // reference-only class
    "RBS::UnitTest::Convertibles::Each", // reference-only class
    "RBS::UnitTest::Convertibles::ToA", // reference-only class
    "RBS::UnitTest::Convertibles::ToArray", // reference-only class
    "RBS::UnitTest::Convertibles::ToC", // reference-only class
    "RBS::UnitTest::Convertibles::ToF", // reference-only class
    "RBS::UnitTest::Convertibles::ToHash", // reference-only class
    "RBS::UnitTest::Convertibles::ToI", // reference-only class
    "RBS::UnitTest::Convertibles::ToIO", // reference-only class
    "RBS::UnitTest::Convertibles::ToInt", // reference-only class
    "RBS::UnitTest::Convertibles::ToPath", // reference-only class
    "RBS::UnitTest::Convertibles::ToR", // reference-only class
    "RBS::UnitTest::Convertibles::ToS", // reference-only class
    "RBS::UnitTest::Convertibles::ToStr", // reference-only class
    "RBS::UnitTest::Convertibles::ToSym", // reference-only class
    "RBS::UnitTest::Spy", // reference-only module
    "RBS::UnitTest::Spy::WrapSpy", // reference-only class
    "RBS::UnitTest::Spy::WrapSpy::NO_RETURN", // constant on the reference only
    "RBS::UnitTest::TypeAssertions", // reference-only module
    "RBS::UnitTest::TypeAssertions::ClassMethods", // reference-only module
    "RBS::UnitTest::TypeAssertions::_BaseAssertions", // reference-only interface
    "RBS::UnitTest::TypeAssertions::target_type", // type alias on the reference only
    "RBS::UnitTest::WithAliases", // reference-only module
    "RBS::UnitTest::WithAliases::WithEnum", // reference-only class
    "RBS::UnknownMethodAliasError", // reference-only class
    "RBS::VERSION", // constant on the reference only
    "RBS::Validator", // reference-only class
    "RBS::VariableDuplicationError", // reference-only class
    "RBS::VarianceCalculator", // reference-only class
    "RBS::VarianceCalculator::Result", // reference-only class
    "RBS::VarianceCalculator::variance", // type alias on the reference only
    "RBS::Vendorer", // reference-only class
    "RBS::WASM", // reference-only module
    "RBS::WASM::Deserializer", // reference-only class
    "RBS::WASM::SerializationSchema", // reference-only module
    "RBS::WASM::SerializationSchema::SCHEMA", // constant on the reference only
    "RBS::WASM::SerializationSchema::SYMBOL_TAG", // constant on the reference only
    "RBS::Writer", // reference-only class
    "RBS::Writer::_IO", // reference-only interface
    "RBS::Writer::_Located", // reference-only interface
    "RBS::_HashEqual", // reference-only interface
    "RBS::_Location", // reference-only interface
    "RBS::_MethodName", // reference-only interface
    "RDoc", // reference-only module
    "RDoc::Alias", // reference-only class
    "RDoc::AnyMethod", // reference-only class
    "RDoc::Attr", // reference-only class
    "RDoc::ClassModule", // reference-only class
    "RDoc::CodeObject", // reference-only class
    "RDoc::Comment", // reference-only class
    "RDoc::Constant", // reference-only class
    "RDoc::Context", // reference-only class
    "RDoc::Context::TOMDOC_TITLES", // constant on the reference only
    "RDoc::Context::TYPES", // constant on the reference only
    "RDoc::Context::class_types", // type alias on the reference only
    "RDoc::Extend", // reference-only class
    "RDoc::Include", // reference-only class
    "RDoc::Markup", // reference-only class
    "RDoc::Markup::Document", // reference-only class
    "RDoc::Markup::ToMarkdown", // reference-only class
    "RDoc::MethodAttr", // reference-only class
    "RDoc::Mixin", // reference-only class
    "RDoc::NormalClass", // reference-only class
    "RDoc::NormalModule", // reference-only class
    "RDoc::Options", // reference-only class
    "RDoc::Parser", // reference-only class
    "RDoc::Parser::RBS", // reference-only class
    "RDoc::RI", // reference-only module
    "RDoc::RI::Paths", // reference-only module
    "RDoc::RI::Paths::gem_filter", // type alias on the reference only
    "RDoc::RI::Paths::path_type", // type alias on the reference only
    "RDoc::SingleClass", // reference-only class
    "RDoc::Stats", // reference-only class
    "RDoc::Store", // reference-only class
    "RDoc::TokenStream", // reference-only module
    "RDoc::TopLevel", // reference-only class
    "RDoc::TopLevel::MARSHAL_VERSION", // constant on the reference only
];
