# GENERATED by `python3 harness/gen_effects_mutator_corpus.py` — DO NOT EDIT.
#
# Source: crates/rigor-effects/vendor/effects/mutators.yml — the VENDORED
# by-reference mutator sets, i.e. the bytes the measured binary compiles in
# (array 31, hash 15, string 26), plus crates/rigor-effects/vendor/effects/core.yml
# for the two catalogue-row control sections.
#
# The MUTATOR-SET coverage gate (issue #110). `mutators.yml` carries 72
# (set, selector) pairs and the collector's mutation judgment is their only
# consumer, yet the rest of harness/effects-corpus touches two of them. That is
# the shape that shipped the posture over-claim (#106): a vendored data table
# read by the collector with no corpus generated FROM the table.
#
# Nothing here encodes what either engine ANSWERS. Every selector in the vendored
# file gets the same four receiver shapes — the ones upstream's
# `MutationClassifier` separates — and `harness/effects_diff.py` reports the
# verdict. A re-vendor that adds a selector adds its probes for free.
#
# `TypeFree` / `TypeFreeSingleton` are the type-free half: `[]=` and its
# attribute-writer twin need no receiver class on either side, so they are where
# the port proves `mutate.*` today and where an ownership divergence would
# surface as an OVER. `Rowed` and `Suppressed` are the must-still-fire and
# must-still-suppress controls, both derived from the catalogue.

# --- the CONSTANT receivers, one per probe ------------------------------
#
# Seeded by the set's own literal, exactly as the `Owned` locals are, so the
# reference types them and the only thing the differential can be reading is
# the ownership judgment.

K_A_SHOVEL = []
K_A_PUSH = []
K_A_APPEND = []
K_A_PREPEND = []
K_A_UNSHIFT = []
K_A_CONCAT = []
K_A_INSERT = []
K_A_POP = []
K_A_SHIFT = []
K_A_DELETE = []
K_A_DELETE_AT = []
K_A_DELETE_IF = []
K_A_REJECT_BANG = []
K_A_CLEAR = []
K_A_COMPACT_BANG = []
K_A_REPLACE = []
K_A_FILL = []
K_A_INDEX_SET = []
K_A_MAP_BANG = []
K_A_COLLECT_BANG = []
K_A_SELECT_BANG = []
K_A_FILTER_BANG = []
K_A_KEEP_IF = []
K_A_UNIQ_BANG = []
K_A_FLATTEN_BANG = []
K_A_SORT_BANG = []
K_A_SORT_BY_BANG = []
K_A_REVERSE_BANG = []
K_A_ROTATE_BANG = []
K_A_SHUFFLE_BANG = []
K_A_SLICE_BANG = []
K_H_INDEX_SET = {}
K_H_STORE = {}
K_H_DELETE = {}
K_H_DELETE_IF = {}
K_H_REJECT_BANG = {}
K_H_SELECT_BANG = {}
K_H_FILTER_BANG = {}
K_H_KEEP_IF = {}
K_H_CLEAR = {}
K_H_COMPACT_BANG = {}
K_H_MERGE_BANG = {}
K_H_UPDATE = {}
K_H_TRANSFORM_KEYS_BANG = {}
K_H_TRANSFORM_VALUES_BANG = {}
K_H_REPLACE = {}
K_S_SHOVEL = +""
K_S_CONCAT = +""
K_S_REPLACE = +""
K_S_INSERT = +""
K_S_PREPEND = +""
K_S_CLEAR = +""
K_S_UPCASE_BANG = +""
K_S_DOWNCASE_BANG = +""
K_S_CAPITALIZE_BANG = +""
K_S_SWAPCASE_BANG = +""
K_S_REVERSE_BANG = +""
K_S_STRIP_BANG = +""
K_S_LSTRIP_BANG = +""
K_S_RSTRIP_BANG = +""
K_S_CHOMP_BANG = +""
K_S_CHOP_BANG = +""
K_S_SQUEEZE_BANG = +""
K_S_SUCC_BANG = +""
K_S_NEXT_BANG = +""
K_S_SUB_BANG = +""
K_S_GSUB_BANG = +""
K_S_TR_BANG = +""
K_S_TR_S_BANG = +""
K_S_DELETE_BANG = +""
K_S_SLICE_BANG = +""
K_S_INDEX_SET = +""

# The `TypeFree` constant receiver — one shared read; a constant carries no
# per-site state.
K_TYPE_FREE = []

# --- the PROVABLY-OWNED receiver ---------------------------------------------
#
# One method per vendored (set, selector) pair (72). The local is seeded by
# the set's own literal, so the reference's typer names the class the set
# belongs to, and it never escapes, so `LocalOwnership#owned` proves it —
# the one shape in which upstream proves `mutate.local` for a set member.
# A `nil` tail is load-bearing: a trailing bare read is an escape
# (`local_ownership.rb:122`), which is what the `Unowned` section below is.

class Owned
  # array: <<
  def a_shovel
    recv = []
    recv << 1
    nil
  end

  # array: push
  def a_push
    recv = []
    recv.push
    nil
  end

  # array: append
  def a_append
    recv = []
    recv.append
    nil
  end

  # array: prepend
  def a_prepend
    recv = []
    recv.prepend
    nil
  end

  # array: unshift
  def a_unshift
    recv = []
    recv.unshift
    nil
  end

  # array: concat
  def a_concat
    recv = []
    recv.concat
    nil
  end

  # array: insert
  def a_insert
    recv = []
    recv.insert
    nil
  end

  # array: pop
  def a_pop
    recv = []
    recv.pop
    nil
  end

  # array: shift
  def a_shift
    recv = []
    recv.shift
    nil
  end

  # array: delete
  def a_delete
    recv = []
    recv.delete
    nil
  end

  # array: delete_at
  def a_delete_at
    recv = []
    recv.delete_at
    nil
  end

  # array: delete_if
  def a_delete_if
    recv = []
    recv.delete_if
    nil
  end

  # array: reject!
  def a_reject_bang
    recv = []
    recv.reject!
    nil
  end

  # array: clear
  def a_clear
    recv = []
    recv.clear
    nil
  end

  # array: compact!
  def a_compact_bang
    recv = []
    recv.compact!
    nil
  end

  # array: replace
  def a_replace
    recv = []
    recv.replace
    nil
  end

  # array: fill
  def a_fill
    recv = []
    recv.fill
    nil
  end

  # array: []=
  def a_index_set
    recv = []
    recv[0] = 1
    nil
  end

  # array: map!
  def a_map_bang
    recv = []
    recv.map!
    nil
  end

  # array: collect!
  def a_collect_bang
    recv = []
    recv.collect!
    nil
  end

  # array: select!
  def a_select_bang
    recv = []
    recv.select!
    nil
  end

  # array: filter!
  def a_filter_bang
    recv = []
    recv.filter!
    nil
  end

  # array: keep_if
  def a_keep_if
    recv = []
    recv.keep_if
    nil
  end

  # array: uniq!
  def a_uniq_bang
    recv = []
    recv.uniq!
    nil
  end

  # array: flatten!
  def a_flatten_bang
    recv = []
    recv.flatten!
    nil
  end

  # array: sort!
  def a_sort_bang
    recv = []
    recv.sort!
    nil
  end

  # array: sort_by!
  def a_sort_by_bang
    recv = []
    recv.sort_by!
    nil
  end

  # array: reverse!
  def a_reverse_bang
    recv = []
    recv.reverse!
    nil
  end

  # array: rotate!
  def a_rotate_bang
    recv = []
    recv.rotate!
    nil
  end

  # array: shuffle!
  def a_shuffle_bang
    recv = []
    recv.shuffle!
    nil
  end

  # array: slice!
  def a_slice_bang
    recv = []
    recv.slice!
    nil
  end

  # hash: []=
  def h_index_set
    recv = {}
    recv[0] = 1
    nil
  end

  # hash: store
  def h_store
    recv = {}
    recv.store
    nil
  end

  # hash: delete
  def h_delete
    recv = {}
    recv.delete
    nil
  end

  # hash: delete_if
  def h_delete_if
    recv = {}
    recv.delete_if
    nil
  end

  # hash: reject!
  def h_reject_bang
    recv = {}
    recv.reject!
    nil
  end

  # hash: select!
  def h_select_bang
    recv = {}
    recv.select!
    nil
  end

  # hash: filter!
  def h_filter_bang
    recv = {}
    recv.filter!
    nil
  end

  # hash: keep_if
  def h_keep_if
    recv = {}
    recv.keep_if
    nil
  end

  # hash: clear
  def h_clear
    recv = {}
    recv.clear
    nil
  end

  # hash: compact!
  def h_compact_bang
    recv = {}
    recv.compact!
    nil
  end

  # hash: merge!
  def h_merge_bang
    recv = {}
    recv.merge!
    nil
  end

  # hash: update
  def h_update
    recv = {}
    recv.update
    nil
  end

  # hash: transform_keys!
  def h_transform_keys_bang
    recv = {}
    recv.transform_keys!
    nil
  end

  # hash: transform_values!
  def h_transform_values_bang
    recv = {}
    recv.transform_values!
    nil
  end

  # hash: replace
  def h_replace
    recv = {}
    recv.replace
    nil
  end

  # string: <<
  def s_shovel
    recv = +""
    recv << 1
    nil
  end

  # string: concat
  def s_concat
    recv = +""
    recv.concat
    nil
  end

  # string: replace
  def s_replace
    recv = +""
    recv.replace
    nil
  end

  # string: insert
  def s_insert
    recv = +""
    recv.insert
    nil
  end

  # string: prepend
  def s_prepend
    recv = +""
    recv.prepend
    nil
  end

  # string: clear
  def s_clear
    recv = +""
    recv.clear
    nil
  end

  # string: upcase!
  def s_upcase_bang
    recv = +""
    recv.upcase!
    nil
  end

  # string: downcase!
  def s_downcase_bang
    recv = +""
    recv.downcase!
    nil
  end

  # string: capitalize!
  def s_capitalize_bang
    recv = +""
    recv.capitalize!
    nil
  end

  # string: swapcase!
  def s_swapcase_bang
    recv = +""
    recv.swapcase!
    nil
  end

  # string: reverse!
  def s_reverse_bang
    recv = +""
    recv.reverse!
    nil
  end

  # string: strip!
  def s_strip_bang
    recv = +""
    recv.strip!
    nil
  end

  # string: lstrip!
  def s_lstrip_bang
    recv = +""
    recv.lstrip!
    nil
  end

  # string: rstrip!
  def s_rstrip_bang
    recv = +""
    recv.rstrip!
    nil
  end

  # string: chomp!
  def s_chomp_bang
    recv = +""
    recv.chomp!
    nil
  end

  # string: chop!
  def s_chop_bang
    recv = +""
    recv.chop!
    nil
  end

  # string: squeeze!
  def s_squeeze_bang
    recv = +""
    recv.squeeze!
    nil
  end

  # string: succ!
  def s_succ_bang
    recv = +""
    recv.succ!
    nil
  end

  # string: next!
  def s_next_bang
    recv = +""
    recv.next!
    nil
  end

  # string: sub!
  def s_sub_bang
    recv = +""
    recv.sub!
    nil
  end

  # string: gsub!
  def s_gsub_bang
    recv = +""
    recv.gsub!
    nil
  end

  # string: tr!
  def s_tr_bang
    recv = +""
    recv.tr!
    nil
  end

  # string: tr_s!
  def s_tr_s_bang
    recv = +""
    recv.tr_s!
    nil
  end

  # string: delete!
  def s_delete_bang
    recv = +""
    recv.delete!
    nil
  end

  # string: slice!
  def s_slice_bang
    recv = +""
    recv.slice!
    nil
  end

  # string: []=
  def s_index_set
    recv = +""
    recv[0] = 1
    nil
  end
end

# --- the TYPED-but-UNOWNED receiver ------------------------------------------
#
# The same seed and the same call, handed to the caller by the trailing bare
# read. The type is known and the ownership is not, so upstream answers ∅
# plus an `unknown-ownership` taint and NEVER a bare `mutate`
# (`mutation_classifier.rb:20`). A port that guessed an owner here — or that
# answered the parent label — turns every one of these into an OVER.

class Unowned
  # array: <<
  def a_shovel
    recv = []
    recv << 1
    recv
  end

  # array: push
  def a_push
    recv = []
    recv.push
    recv
  end

  # array: append
  def a_append
    recv = []
    recv.append
    recv
  end

  # array: prepend
  def a_prepend
    recv = []
    recv.prepend
    recv
  end

  # array: unshift
  def a_unshift
    recv = []
    recv.unshift
    recv
  end

  # array: concat
  def a_concat
    recv = []
    recv.concat
    recv
  end

  # array: insert
  def a_insert
    recv = []
    recv.insert
    recv
  end

  # array: pop
  def a_pop
    recv = []
    recv.pop
    recv
  end

  # array: shift
  def a_shift
    recv = []
    recv.shift
    recv
  end

  # array: delete
  def a_delete
    recv = []
    recv.delete
    recv
  end

  # array: delete_at
  def a_delete_at
    recv = []
    recv.delete_at
    recv
  end

  # array: delete_if
  def a_delete_if
    recv = []
    recv.delete_if
    recv
  end

  # array: reject!
  def a_reject_bang
    recv = []
    recv.reject!
    recv
  end

  # array: clear
  def a_clear
    recv = []
    recv.clear
    recv
  end

  # array: compact!
  def a_compact_bang
    recv = []
    recv.compact!
    recv
  end

  # array: replace
  def a_replace
    recv = []
    recv.replace
    recv
  end

  # array: fill
  def a_fill
    recv = []
    recv.fill
    recv
  end

  # array: []=
  def a_index_set
    recv = []
    recv[0] = 1
    recv
  end

  # array: map!
  def a_map_bang
    recv = []
    recv.map!
    recv
  end

  # array: collect!
  def a_collect_bang
    recv = []
    recv.collect!
    recv
  end

  # array: select!
  def a_select_bang
    recv = []
    recv.select!
    recv
  end

  # array: filter!
  def a_filter_bang
    recv = []
    recv.filter!
    recv
  end

  # array: keep_if
  def a_keep_if
    recv = []
    recv.keep_if
    recv
  end

  # array: uniq!
  def a_uniq_bang
    recv = []
    recv.uniq!
    recv
  end

  # array: flatten!
  def a_flatten_bang
    recv = []
    recv.flatten!
    recv
  end

  # array: sort!
  def a_sort_bang
    recv = []
    recv.sort!
    recv
  end

  # array: sort_by!
  def a_sort_by_bang
    recv = []
    recv.sort_by!
    recv
  end

  # array: reverse!
  def a_reverse_bang
    recv = []
    recv.reverse!
    recv
  end

  # array: rotate!
  def a_rotate_bang
    recv = []
    recv.rotate!
    recv
  end

  # array: shuffle!
  def a_shuffle_bang
    recv = []
    recv.shuffle!
    recv
  end

  # array: slice!
  def a_slice_bang
    recv = []
    recv.slice!
    recv
  end

  # hash: []=
  def h_index_set
    recv = {}
    recv[0] = 1
    recv
  end

  # hash: store
  def h_store
    recv = {}
    recv.store
    recv
  end

  # hash: delete
  def h_delete
    recv = {}
    recv.delete
    recv
  end

  # hash: delete_if
  def h_delete_if
    recv = {}
    recv.delete_if
    recv
  end

  # hash: reject!
  def h_reject_bang
    recv = {}
    recv.reject!
    recv
  end

  # hash: select!
  def h_select_bang
    recv = {}
    recv.select!
    recv
  end

  # hash: filter!
  def h_filter_bang
    recv = {}
    recv.filter!
    recv
  end

  # hash: keep_if
  def h_keep_if
    recv = {}
    recv.keep_if
    recv
  end

  # hash: clear
  def h_clear
    recv = {}
    recv.clear
    recv
  end

  # hash: compact!
  def h_compact_bang
    recv = {}
    recv.compact!
    recv
  end

  # hash: merge!
  def h_merge_bang
    recv = {}
    recv.merge!
    recv
  end

  # hash: update
  def h_update
    recv = {}
    recv.update
    recv
  end

  # hash: transform_keys!
  def h_transform_keys_bang
    recv = {}
    recv.transform_keys!
    recv
  end

  # hash: transform_values!
  def h_transform_values_bang
    recv = {}
    recv.transform_values!
    recv
  end

  # hash: replace
  def h_replace
    recv = {}
    recv.replace
    recv
  end

  # string: <<
  def s_shovel
    recv = +""
    recv << 1
    recv
  end

  # string: concat
  def s_concat
    recv = +""
    recv.concat
    recv
  end

  # string: replace
  def s_replace
    recv = +""
    recv.replace
    recv
  end

  # string: insert
  def s_insert
    recv = +""
    recv.insert
    recv
  end

  # string: prepend
  def s_prepend
    recv = +""
    recv.prepend
    recv
  end

  # string: clear
  def s_clear
    recv = +""
    recv.clear
    recv
  end

  # string: upcase!
  def s_upcase_bang
    recv = +""
    recv.upcase!
    recv
  end

  # string: downcase!
  def s_downcase_bang
    recv = +""
    recv.downcase!
    recv
  end

  # string: capitalize!
  def s_capitalize_bang
    recv = +""
    recv.capitalize!
    recv
  end

  # string: swapcase!
  def s_swapcase_bang
    recv = +""
    recv.swapcase!
    recv
  end

  # string: reverse!
  def s_reverse_bang
    recv = +""
    recv.reverse!
    recv
  end

  # string: strip!
  def s_strip_bang
    recv = +""
    recv.strip!
    recv
  end

  # string: lstrip!
  def s_lstrip_bang
    recv = +""
    recv.lstrip!
    recv
  end

  # string: rstrip!
  def s_rstrip_bang
    recv = +""
    recv.rstrip!
    recv
  end

  # string: chomp!
  def s_chomp_bang
    recv = +""
    recv.chomp!
    recv
  end

  # string: chop!
  def s_chop_bang
    recv = +""
    recv.chop!
    recv
  end

  # string: squeeze!
  def s_squeeze_bang
    recv = +""
    recv.squeeze!
    recv
  end

  # string: succ!
  def s_succ_bang
    recv = +""
    recv.succ!
    recv
  end

  # string: next!
  def s_next_bang
    recv = +""
    recv.next!
    recv
  end

  # string: sub!
  def s_sub_bang
    recv = +""
    recv.sub!
    recv
  end

  # string: gsub!
  def s_gsub_bang
    recv = +""
    recv.gsub!
    recv
  end

  # string: tr!
  def s_tr_bang
    recv = +""
    recv.tr!
    recv
  end

  # string: tr_s!
  def s_tr_s_bang
    recv = +""
    recv.tr_s!
    recv
  end

  # string: delete!
  def s_delete_bang
    recv = +""
    recv.delete!
    recv
  end

  # string: slice!
  def s_slice_bang
    recv = +""
    recv.slice!
    recv
  end

  # string: []=
  def s_index_set
    recv = +""
    recv[0] = 1
    recv
  end
end

# --- the IVAR receiver -------------------------------------------------------
#
# `@recv` is seeded in the body so the reference can type it. Both the write
# and the mutation earn `mutate.self`, so the PROVEN lane is the same one
# label either way and a mis-owned mutation (`mutate.local` on an ivar, say)
# shows up as an OVER rather than as silence.

class Ivar
  # array: <<
  def a_shovel
    @recv = []
    @recv << 1
    nil
  end

  # array: push
  def a_push
    @recv = []
    @recv.push
    nil
  end

  # array: append
  def a_append
    @recv = []
    @recv.append
    nil
  end

  # array: prepend
  def a_prepend
    @recv = []
    @recv.prepend
    nil
  end

  # array: unshift
  def a_unshift
    @recv = []
    @recv.unshift
    nil
  end

  # array: concat
  def a_concat
    @recv = []
    @recv.concat
    nil
  end

  # array: insert
  def a_insert
    @recv = []
    @recv.insert
    nil
  end

  # array: pop
  def a_pop
    @recv = []
    @recv.pop
    nil
  end

  # array: shift
  def a_shift
    @recv = []
    @recv.shift
    nil
  end

  # array: delete
  def a_delete
    @recv = []
    @recv.delete
    nil
  end

  # array: delete_at
  def a_delete_at
    @recv = []
    @recv.delete_at
    nil
  end

  # array: delete_if
  def a_delete_if
    @recv = []
    @recv.delete_if
    nil
  end

  # array: reject!
  def a_reject_bang
    @recv = []
    @recv.reject!
    nil
  end

  # array: clear
  def a_clear
    @recv = []
    @recv.clear
    nil
  end

  # array: compact!
  def a_compact_bang
    @recv = []
    @recv.compact!
    nil
  end

  # array: replace
  def a_replace
    @recv = []
    @recv.replace
    nil
  end

  # array: fill
  def a_fill
    @recv = []
    @recv.fill
    nil
  end

  # array: []=
  def a_index_set
    @recv = []
    @recv[0] = 1
    nil
  end

  # array: map!
  def a_map_bang
    @recv = []
    @recv.map!
    nil
  end

  # array: collect!
  def a_collect_bang
    @recv = []
    @recv.collect!
    nil
  end

  # array: select!
  def a_select_bang
    @recv = []
    @recv.select!
    nil
  end

  # array: filter!
  def a_filter_bang
    @recv = []
    @recv.filter!
    nil
  end

  # array: keep_if
  def a_keep_if
    @recv = []
    @recv.keep_if
    nil
  end

  # array: uniq!
  def a_uniq_bang
    @recv = []
    @recv.uniq!
    nil
  end

  # array: flatten!
  def a_flatten_bang
    @recv = []
    @recv.flatten!
    nil
  end

  # array: sort!
  def a_sort_bang
    @recv = []
    @recv.sort!
    nil
  end

  # array: sort_by!
  def a_sort_by_bang
    @recv = []
    @recv.sort_by!
    nil
  end

  # array: reverse!
  def a_reverse_bang
    @recv = []
    @recv.reverse!
    nil
  end

  # array: rotate!
  def a_rotate_bang
    @recv = []
    @recv.rotate!
    nil
  end

  # array: shuffle!
  def a_shuffle_bang
    @recv = []
    @recv.shuffle!
    nil
  end

  # array: slice!
  def a_slice_bang
    @recv = []
    @recv.slice!
    nil
  end

  # hash: []=
  def h_index_set
    @recv = {}
    @recv[0] = 1
    nil
  end

  # hash: store
  def h_store
    @recv = {}
    @recv.store
    nil
  end

  # hash: delete
  def h_delete
    @recv = {}
    @recv.delete
    nil
  end

  # hash: delete_if
  def h_delete_if
    @recv = {}
    @recv.delete_if
    nil
  end

  # hash: reject!
  def h_reject_bang
    @recv = {}
    @recv.reject!
    nil
  end

  # hash: select!
  def h_select_bang
    @recv = {}
    @recv.select!
    nil
  end

  # hash: filter!
  def h_filter_bang
    @recv = {}
    @recv.filter!
    nil
  end

  # hash: keep_if
  def h_keep_if
    @recv = {}
    @recv.keep_if
    nil
  end

  # hash: clear
  def h_clear
    @recv = {}
    @recv.clear
    nil
  end

  # hash: compact!
  def h_compact_bang
    @recv = {}
    @recv.compact!
    nil
  end

  # hash: merge!
  def h_merge_bang
    @recv = {}
    @recv.merge!
    nil
  end

  # hash: update
  def h_update
    @recv = {}
    @recv.update
    nil
  end

  # hash: transform_keys!
  def h_transform_keys_bang
    @recv = {}
    @recv.transform_keys!
    nil
  end

  # hash: transform_values!
  def h_transform_values_bang
    @recv = {}
    @recv.transform_values!
    nil
  end

  # hash: replace
  def h_replace
    @recv = {}
    @recv.replace
    nil
  end

  # string: <<
  def s_shovel
    @recv = +""
    @recv << 1
    nil
  end

  # string: concat
  def s_concat
    @recv = +""
    @recv.concat
    nil
  end

  # string: replace
  def s_replace
    @recv = +""
    @recv.replace
    nil
  end

  # string: insert
  def s_insert
    @recv = +""
    @recv.insert
    nil
  end

  # string: prepend
  def s_prepend
    @recv = +""
    @recv.prepend
    nil
  end

  # string: clear
  def s_clear
    @recv = +""
    @recv.clear
    nil
  end

  # string: upcase!
  def s_upcase_bang
    @recv = +""
    @recv.upcase!
    nil
  end

  # string: downcase!
  def s_downcase_bang
    @recv = +""
    @recv.downcase!
    nil
  end

  # string: capitalize!
  def s_capitalize_bang
    @recv = +""
    @recv.capitalize!
    nil
  end

  # string: swapcase!
  def s_swapcase_bang
    @recv = +""
    @recv.swapcase!
    nil
  end

  # string: reverse!
  def s_reverse_bang
    @recv = +""
    @recv.reverse!
    nil
  end

  # string: strip!
  def s_strip_bang
    @recv = +""
    @recv.strip!
    nil
  end

  # string: lstrip!
  def s_lstrip_bang
    @recv = +""
    @recv.lstrip!
    nil
  end

  # string: rstrip!
  def s_rstrip_bang
    @recv = +""
    @recv.rstrip!
    nil
  end

  # string: chomp!
  def s_chomp_bang
    @recv = +""
    @recv.chomp!
    nil
  end

  # string: chop!
  def s_chop_bang
    @recv = +""
    @recv.chop!
    nil
  end

  # string: squeeze!
  def s_squeeze_bang
    @recv = +""
    @recv.squeeze!
    nil
  end

  # string: succ!
  def s_succ_bang
    @recv = +""
    @recv.succ!
    nil
  end

  # string: next!
  def s_next_bang
    @recv = +""
    @recv.next!
    nil
  end

  # string: sub!
  def s_sub_bang
    @recv = +""
    @recv.sub!
    nil
  end

  # string: gsub!
  def s_gsub_bang
    @recv = +""
    @recv.gsub!
    nil
  end

  # string: tr!
  def s_tr_bang
    @recv = +""
    @recv.tr!
    nil
  end

  # string: tr_s!
  def s_tr_s_bang
    @recv = +""
    @recv.tr_s!
    nil
  end

  # string: delete!
  def s_delete_bang
    @recv = +""
    @recv.delete!
    nil
  end

  # string: slice!
  def s_slice_bang
    @recv = +""
    @recv.slice!
    nil
  end

  # string: []=
  def s_index_set
    @recv = +""
    @recv[0] = 1
    nil
  end
end

# --- the CONSTANT receiver ---------------------------------------------------
#
# `label_for` recognises nil/self, ivar and cvar reads, parameters and
# frame-owned locals — a constant is none of them, so ownership is never
# provable and upstream answers ∅ + `unknown-ownership` however precisely it
# typed the receiver. The constants are seeded at the top of this file.

class Konstant
  # array: <<
  def a_shovel
    K_A_SHOVEL << 1
    nil
  end

  # array: push
  def a_push
    K_A_PUSH.push
    nil
  end

  # array: append
  def a_append
    K_A_APPEND.append
    nil
  end

  # array: prepend
  def a_prepend
    K_A_PREPEND.prepend
    nil
  end

  # array: unshift
  def a_unshift
    K_A_UNSHIFT.unshift
    nil
  end

  # array: concat
  def a_concat
    K_A_CONCAT.concat
    nil
  end

  # array: insert
  def a_insert
    K_A_INSERT.insert
    nil
  end

  # array: pop
  def a_pop
    K_A_POP.pop
    nil
  end

  # array: shift
  def a_shift
    K_A_SHIFT.shift
    nil
  end

  # array: delete
  def a_delete
    K_A_DELETE.delete
    nil
  end

  # array: delete_at
  def a_delete_at
    K_A_DELETE_AT.delete_at
    nil
  end

  # array: delete_if
  def a_delete_if
    K_A_DELETE_IF.delete_if
    nil
  end

  # array: reject!
  def a_reject_bang
    K_A_REJECT_BANG.reject!
    nil
  end

  # array: clear
  def a_clear
    K_A_CLEAR.clear
    nil
  end

  # array: compact!
  def a_compact_bang
    K_A_COMPACT_BANG.compact!
    nil
  end

  # array: replace
  def a_replace
    K_A_REPLACE.replace
    nil
  end

  # array: fill
  def a_fill
    K_A_FILL.fill
    nil
  end

  # array: []=
  def a_index_set
    K_A_INDEX_SET[0] = 1
    nil
  end

  # array: map!
  def a_map_bang
    K_A_MAP_BANG.map!
    nil
  end

  # array: collect!
  def a_collect_bang
    K_A_COLLECT_BANG.collect!
    nil
  end

  # array: select!
  def a_select_bang
    K_A_SELECT_BANG.select!
    nil
  end

  # array: filter!
  def a_filter_bang
    K_A_FILTER_BANG.filter!
    nil
  end

  # array: keep_if
  def a_keep_if
    K_A_KEEP_IF.keep_if
    nil
  end

  # array: uniq!
  def a_uniq_bang
    K_A_UNIQ_BANG.uniq!
    nil
  end

  # array: flatten!
  def a_flatten_bang
    K_A_FLATTEN_BANG.flatten!
    nil
  end

  # array: sort!
  def a_sort_bang
    K_A_SORT_BANG.sort!
    nil
  end

  # array: sort_by!
  def a_sort_by_bang
    K_A_SORT_BY_BANG.sort_by!
    nil
  end

  # array: reverse!
  def a_reverse_bang
    K_A_REVERSE_BANG.reverse!
    nil
  end

  # array: rotate!
  def a_rotate_bang
    K_A_ROTATE_BANG.rotate!
    nil
  end

  # array: shuffle!
  def a_shuffle_bang
    K_A_SHUFFLE_BANG.shuffle!
    nil
  end

  # array: slice!
  def a_slice_bang
    K_A_SLICE_BANG.slice!
    nil
  end

  # hash: []=
  def h_index_set
    K_H_INDEX_SET[0] = 1
    nil
  end

  # hash: store
  def h_store
    K_H_STORE.store
    nil
  end

  # hash: delete
  def h_delete
    K_H_DELETE.delete
    nil
  end

  # hash: delete_if
  def h_delete_if
    K_H_DELETE_IF.delete_if
    nil
  end

  # hash: reject!
  def h_reject_bang
    K_H_REJECT_BANG.reject!
    nil
  end

  # hash: select!
  def h_select_bang
    K_H_SELECT_BANG.select!
    nil
  end

  # hash: filter!
  def h_filter_bang
    K_H_FILTER_BANG.filter!
    nil
  end

  # hash: keep_if
  def h_keep_if
    K_H_KEEP_IF.keep_if
    nil
  end

  # hash: clear
  def h_clear
    K_H_CLEAR.clear
    nil
  end

  # hash: compact!
  def h_compact_bang
    K_H_COMPACT_BANG.compact!
    nil
  end

  # hash: merge!
  def h_merge_bang
    K_H_MERGE_BANG.merge!
    nil
  end

  # hash: update
  def h_update
    K_H_UPDATE.update
    nil
  end

  # hash: transform_keys!
  def h_transform_keys_bang
    K_H_TRANSFORM_KEYS_BANG.transform_keys!
    nil
  end

  # hash: transform_values!
  def h_transform_values_bang
    K_H_TRANSFORM_VALUES_BANG.transform_values!
    nil
  end

  # hash: replace
  def h_replace
    K_H_REPLACE.replace
    nil
  end

  # string: <<
  def s_shovel
    K_S_SHOVEL << 1
    nil
  end

  # string: concat
  def s_concat
    K_S_CONCAT.concat
    nil
  end

  # string: replace
  def s_replace
    K_S_REPLACE.replace
    nil
  end

  # string: insert
  def s_insert
    K_S_INSERT.insert
    nil
  end

  # string: prepend
  def s_prepend
    K_S_PREPEND.prepend
    nil
  end

  # string: clear
  def s_clear
    K_S_CLEAR.clear
    nil
  end

  # string: upcase!
  def s_upcase_bang
    K_S_UPCASE_BANG.upcase!
    nil
  end

  # string: downcase!
  def s_downcase_bang
    K_S_DOWNCASE_BANG.downcase!
    nil
  end

  # string: capitalize!
  def s_capitalize_bang
    K_S_CAPITALIZE_BANG.capitalize!
    nil
  end

  # string: swapcase!
  def s_swapcase_bang
    K_S_SWAPCASE_BANG.swapcase!
    nil
  end

  # string: reverse!
  def s_reverse_bang
    K_S_REVERSE_BANG.reverse!
    nil
  end

  # string: strip!
  def s_strip_bang
    K_S_STRIP_BANG.strip!
    nil
  end

  # string: lstrip!
  def s_lstrip_bang
    K_S_LSTRIP_BANG.lstrip!
    nil
  end

  # string: rstrip!
  def s_rstrip_bang
    K_S_RSTRIP_BANG.rstrip!
    nil
  end

  # string: chomp!
  def s_chomp_bang
    K_S_CHOMP_BANG.chomp!
    nil
  end

  # string: chop!
  def s_chop_bang
    K_S_CHOP_BANG.chop!
    nil
  end

  # string: squeeze!
  def s_squeeze_bang
    K_S_SQUEEZE_BANG.squeeze!
    nil
  end

  # string: succ!
  def s_succ_bang
    K_S_SUCC_BANG.succ!
    nil
  end

  # string: next!
  def s_next_bang
    K_S_NEXT_BANG.next!
    nil
  end

  # string: sub!
  def s_sub_bang
    K_S_SUB_BANG.sub!
    nil
  end

  # string: gsub!
  def s_gsub_bang
    K_S_GSUB_BANG.gsub!
    nil
  end

  # string: tr!
  def s_tr_bang
    K_S_TR_BANG.tr!
    nil
  end

  # string: tr_s!
  def s_tr_s_bang
    K_S_TR_S_BANG.tr_s!
    nil
  end

  # string: delete!
  def s_delete_bang
    K_S_DELETE_BANG.delete!
    nil
  end

  # string: slice!
  def s_slice_bang
    K_S_SLICE_BANG.slice!
    nil
  end

  # string: []=
  def s_index_set
    K_S_INDEX_SET[0] = 1
    nil
  end
end

# --- TYPE-FREE: `[]=` and the attribute writer, on every receiver shape ------
#
# `[]=` is a member of all three vendored sets AND of upstream's
# `UNIVERSAL_MUTATORS`, so it is claimed on every receiver with no class
# needed; `slot=` is its twin through `ATTRIBUTE_WRITER`. Eight spellings
# each: the two plain calls plus the six compound-write node types the
# collector branches on individually, which bypass the catalogue entirely
# and so are pure ownership readings on both sides.
#
# This is the section where the port PROVES `mutate.*` today, so it is the
# one an ownership divergence would surface in — as an OVER, not as silence.

class TypeFree
  # a frame-owned local: mutate.local — the plain `[]=` call
  def owned_index_set
    recv = []
    recv[0] = 1
    nil
  end

  # a frame-owned local: mutate.local — IndexOperatorWriteNode
  def owned_index_op
    recv = []
    recv[0] += 1
    nil
  end

  # a frame-owned local: mutate.local — IndexOrWriteNode
  def owned_index_or
    recv = []
    recv[0] ||= 1
    nil
  end

  # a frame-owned local: mutate.local — IndexAndWriteNode
  def owned_index_and
    recv = []
    recv[0] &&= 1
    nil
  end

  # a frame-owned local: mutate.local — the plain attribute-writer call
  def owned_writer
    recv = []
    recv.slot = 1
    nil
  end

  # a frame-owned local: mutate.local — CallOperatorWriteNode
  def owned_writer_op
    recv = []
    recv.slot += 1
    nil
  end

  # a frame-owned local: mutate.local — CallOrWriteNode
  def owned_writer_or
    recv = []
    recv.slot ||= 1
    nil
  end

  # a frame-owned local: mutate.local — CallAndWriteNode
  def owned_writer_and
    recv = []
    recv.slot &&= 1
    nil
  end

  # the same local, handed to the caller: ownership unprovable — the plain `[]=` call
  def escaping_index_set
    recv = []
    recv[0] = 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — IndexOperatorWriteNode
  def escaping_index_op
    recv = []
    recv[0] += 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — IndexOrWriteNode
  def escaping_index_or
    recv = []
    recv[0] ||= 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — IndexAndWriteNode
  def escaping_index_and
    recv = []
    recv[0] &&= 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — the plain attribute-writer call
  def escaping_writer
    recv = []
    recv.slot = 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — CallOperatorWriteNode
  def escaping_writer_op
    recv = []
    recv.slot += 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — CallOrWriteNode
  def escaping_writer_or
    recv = []
    recv.slot ||= 1
    recv
  end

  # the same local, handed to the caller: ownership unprovable — CallAndWriteNode
  def escaping_writer_and
    recv = []
    recv.slot &&= 1
    recv
  end

  # a parameter: mutate.instance — the plain `[]=` call
  def param_index_set(recv)
    recv[0] = 1
    nil
  end

  # a parameter: mutate.instance — IndexOperatorWriteNode
  def param_index_op(recv)
    recv[0] += 1
    nil
  end

  # a parameter: mutate.instance — IndexOrWriteNode
  def param_index_or(recv)
    recv[0] ||= 1
    nil
  end

  # a parameter: mutate.instance — IndexAndWriteNode
  def param_index_and(recv)
    recv[0] &&= 1
    nil
  end

  # a parameter: mutate.instance — the plain attribute-writer call
  def param_writer(recv)
    recv.slot = 1
    nil
  end

  # a parameter: mutate.instance — CallOperatorWriteNode
  def param_writer_op(recv)
    recv.slot += 1
    nil
  end

  # a parameter: mutate.instance — CallOrWriteNode
  def param_writer_or(recv)
    recv.slot ||= 1
    nil
  end

  # a parameter: mutate.instance — CallAndWriteNode
  def param_writer_and(recv)
    recv.slot &&= 1
    nil
  end

  # an ivar read: mutate.self — the plain `[]=` call
  def ivar_index_set
    @recv = []
    @recv[0] = 1
    nil
  end

  # an ivar read: mutate.self — IndexOperatorWriteNode
  def ivar_index_op
    @recv = []
    @recv[0] += 1
    nil
  end

  # an ivar read: mutate.self — IndexOrWriteNode
  def ivar_index_or
    @recv = []
    @recv[0] ||= 1
    nil
  end

  # an ivar read: mutate.self — IndexAndWriteNode
  def ivar_index_and
    @recv = []
    @recv[0] &&= 1
    nil
  end

  # an ivar read: mutate.self — the plain attribute-writer call
  def ivar_writer
    @recv = []
    @recv.slot = 1
    nil
  end

  # an ivar read: mutate.self — CallOperatorWriteNode
  def ivar_writer_op
    @recv = []
    @recv.slot += 1
    nil
  end

  # an ivar read: mutate.self — CallOrWriteNode
  def ivar_writer_or
    @recv = []
    @recv.slot ||= 1
    nil
  end

  # an ivar read: mutate.self — CallAndWriteNode
  def ivar_writer_and
    @recv = []
    @recv.slot &&= 1
    nil
  end

  # a cvar read: mutate.static — the plain `[]=` call
  def cvar_index_set
    @@recv = []
    @@recv[0] = 1
    nil
  end

  # a cvar read: mutate.static — IndexOperatorWriteNode
  def cvar_index_op
    @@recv = []
    @@recv[0] += 1
    nil
  end

  # a cvar read: mutate.static — IndexOrWriteNode
  def cvar_index_or
    @@recv = []
    @@recv[0] ||= 1
    nil
  end

  # a cvar read: mutate.static — IndexAndWriteNode
  def cvar_index_and
    @@recv = []
    @@recv[0] &&= 1
    nil
  end

  # a cvar read: mutate.static — the plain attribute-writer call
  def cvar_writer
    @@recv = []
    @@recv.slot = 1
    nil
  end

  # a cvar read: mutate.static — CallOperatorWriteNode
  def cvar_writer_op
    @@recv = []
    @@recv.slot += 1
    nil
  end

  # a cvar read: mutate.static — CallOrWriteNode
  def cvar_writer_or
    @@recv = []
    @@recv.slot ||= 1
    nil
  end

  # a cvar read: mutate.static — CallAndWriteNode
  def cvar_writer_and
    @@recv = []
    @@recv.slot &&= 1
    nil
  end

  # a constant: never provable — the plain `[]=` call
  def konstant_index_set
    K_TYPE_FREE[0] = 1
    nil
  end

  # a constant: never provable — IndexOperatorWriteNode
  def konstant_index_op
    K_TYPE_FREE[0] += 1
    nil
  end

  # a constant: never provable — IndexOrWriteNode
  def konstant_index_or
    K_TYPE_FREE[0] ||= 1
    nil
  end

  # a constant: never provable — IndexAndWriteNode
  def konstant_index_and
    K_TYPE_FREE[0] &&= 1
    nil
  end

  # a constant: never provable — the plain attribute-writer call
  def konstant_writer
    K_TYPE_FREE.slot = 1
    nil
  end

  # a constant: never provable — CallOperatorWriteNode
  def konstant_writer_op
    K_TYPE_FREE.slot += 1
    nil
  end

  # a constant: never provable — CallOrWriteNode
  def konstant_writer_or
    K_TYPE_FREE.slot ||= 1
    nil
  end

  # a constant: never provable — CallAndWriteNode
  def konstant_writer_and
    K_TYPE_FREE.slot &&= 1
    nil
  end

  # self: mutate.self — the plain `[]=` call
  def selfrecv_index_set
    self[0] = 1
    nil
  end

  # self: mutate.self — IndexOperatorWriteNode
  def selfrecv_index_op
    self[0] += 1
    nil
  end

  # self: mutate.self — IndexOrWriteNode
  def selfrecv_index_or
    self[0] ||= 1
    nil
  end

  # self: mutate.self — IndexAndWriteNode
  def selfrecv_index_and
    self[0] &&= 1
    nil
  end

  # self: mutate.self — the plain attribute-writer call
  def selfrecv_writer
    self.slot = 1
    nil
  end

  # self: mutate.self — CallOperatorWriteNode
  def selfrecv_writer_op
    self.slot += 1
    nil
  end

  # self: mutate.self — CallOrWriteNode
  def selfrecv_writer_or
    self.slot ||= 1
    nil
  end

  # self: mutate.self — CallAndWriteNode
  def selfrecv_writer_and
    self.slot &&= 1
    nil
  end
end

# --- TYPE-FREE, in a SINGLETON unit ------------------------------------------
#
# `class << self` flips the axis that separates `mutate.self` from
# `mutate.static` for self and its ivars, and leaves a local alone
# (`mutation_classifier.rb:80`). Same eight spellings.

class TypeFreeSingleton
  class << self
    # a frame-owned local: mutate.local — the plain `[]=` call
    def owned_index_set
      recv = []
      recv[0] = 1
      nil
    end

    # a frame-owned local: mutate.local — IndexOperatorWriteNode
    def owned_index_op
      recv = []
      recv[0] += 1
      nil
    end

    # a frame-owned local: mutate.local — IndexOrWriteNode
    def owned_index_or
      recv = []
      recv[0] ||= 1
      nil
    end

    # a frame-owned local: mutate.local — IndexAndWriteNode
    def owned_index_and
      recv = []
      recv[0] &&= 1
      nil
    end

    # a frame-owned local: mutate.local — the plain attribute-writer call
    def owned_writer
      recv = []
      recv.slot = 1
      nil
    end

    # a frame-owned local: mutate.local — CallOperatorWriteNode
    def owned_writer_op
      recv = []
      recv.slot += 1
      nil
    end

    # a frame-owned local: mutate.local — CallOrWriteNode
    def owned_writer_or
      recv = []
      recv.slot ||= 1
      nil
    end

    # a frame-owned local: mutate.local — CallAndWriteNode
    def owned_writer_and
      recv = []
      recv.slot &&= 1
      nil
    end

    # an ivar read: mutate.self — the plain `[]=` call
    def ivar_index_set
      @recv = []
      @recv[0] = 1
      nil
    end

    # an ivar read: mutate.self — IndexOperatorWriteNode
    def ivar_index_op
      @recv = []
      @recv[0] += 1
      nil
    end

    # an ivar read: mutate.self — IndexOrWriteNode
    def ivar_index_or
      @recv = []
      @recv[0] ||= 1
      nil
    end

    # an ivar read: mutate.self — IndexAndWriteNode
    def ivar_index_and
      @recv = []
      @recv[0] &&= 1
      nil
    end

    # an ivar read: mutate.self — the plain attribute-writer call
    def ivar_writer
      @recv = []
      @recv.slot = 1
      nil
    end

    # an ivar read: mutate.self — CallOperatorWriteNode
    def ivar_writer_op
      @recv = []
      @recv.slot += 1
      nil
    end

    # an ivar read: mutate.self — CallOrWriteNode
    def ivar_writer_or
      @recv = []
      @recv.slot ||= 1
      nil
    end

    # an ivar read: mutate.self — CallAndWriteNode
    def ivar_writer_and
      @recv = []
      @recv.slot &&= 1
      nil
    end

    # self: mutate.self — the plain `[]=` call
    def selfrecv_index_set
      self[0] = 1
      nil
    end

    # self: mutate.self — IndexOperatorWriteNode
    def selfrecv_index_op
      self[0] += 1
      nil
    end

    # self: mutate.self — IndexOrWriteNode
    def selfrecv_index_or
      self[0] ||= 1
      nil
    end

    # self: mutate.self — IndexAndWriteNode
    def selfrecv_index_and
      self[0] &&= 1
      nil
    end

    # self: mutate.self — the plain attribute-writer call
    def selfrecv_writer
      self.slot = 1
      nil
    end

    # self: mutate.self — CallOperatorWriteNode
    def selfrecv_writer_op
      self.slot += 1
      nil
    end

    # self: mutate.self — CallOrWriteNode
    def selfrecv_writer_or
      self.slot ||= 1
      nil
    end

    # self: mutate.self — CallAndWriteNode
    def selfrecv_writer_and
      self.slot &&= 1
      nil
    end
  end
end

# --- control: a ROWED mutator selector is the ROW's answer, not a mutation ---
#
# Every catalogued row (10) whose selector is in a vendored set and whose
# owner a CONSTANT receiver can spell. `Catalog#lookup` reads the row first
# and a row is not a receiver mutation unless it says so, so `ENV.clear` is
# `global.write` and nothing else — never `mutate.*`. These must stay MATCH:
# a port that let a set membership override a row would show up here as an
# OVER, and one that stopped reading rows would lose every label below.

class Rowed
  # File.delete: io.fs.write
  def r_file_delete
    File.delete
  end

  # Dir.delete: io.fs.write
  def r_dir_delete
    Dir.delete
  end

  # ENV#[]=: global.write
  def r_env_index_set
    ENV[0] = 1
  end

  # ENV#store: global.write
  def r_env_store
    ENV.store
  end

  # ENV#delete: global.write
  def r_env_delete
    ENV.delete
  end

  # ENV#update: global.write
  def r_env_update
    ENV.update
  end

  # ENV#merge!: global.write
  def r_env_merge_bang
    ENV.merge!
  end

  # ENV#replace: global.write
  def r_env_replace
    ENV.replace
  end

  # ENV#clear: global.write
  def r_env_clear
    ENV.clear
  end

  # Warning.[]=: global.write
  def r_warning_index_set
    Warning[0] = 1
  end
end

# --- control: the selectors a row answers as a NON-mutation stay SUPPRESSED ---
#
# The 5 rows behind `NON_MUTATING_ROWED_SELECTORS` (`collect.rs`): a
# universally-mutating selector that some catalogue row answers as a plain
# effect. Upstream reaches those rows through the TYPER, for a receiver this
# port cannot name from syntax — so the port suppresses the label rather
# than mirroring a typing it does not have.
#
# The receiver is made provably-owned wherever the class has an allocator,
# which is what makes the suppression falsifiable: the oracle proves the
# ROW's label, and a port that dropped the suppression would prove
# `mutate.local` beside it — a label the oracle does not prove, i.e. an OVER.

class Suppressed
  # ENV#[]= -> global.write (an object constant has no allocator)
  def s_env_index_set
    recv = ENV
    recv[0] = 1
    nil
  end

  # Thread#[]= -> global.write (a provably-owned instance — the FATAL member)
  def s_thread_index_set
    recv = Thread.new
    recv[0] = 1
    nil
  end

  # Warning#[]= -> global.write (a singleton row: the receiver is the class object)
  def s_warning_index_set
    recv = Warning
    recv[0] = 1
    nil
  end

  # Encoding#default_external= -> global.write (a singleton row: the receiver is the class object)
  def s_encoding_default_external_set
    recv = Encoding
    recv.default_external = 1
    nil
  end

  # Encoding#default_internal= -> global.write (a singleton row: the receiver is the class object)
  def s_encoding_default_internal_set
    recv = Encoding
    recv.default_internal = 1
    nil
  end
end
