# GENERATED by `python3 harness/gen_effects_posture_corpus.py` — DO NOT EDIT.
#
# Source: crates/rigor-effects/vendor/effects/core.yml — the VENDORED catalogue,
# i.e. the bytes the measured binary compiles in.
# schema 1, vocabulary 1, 80 classes.
#
# The POSTURE-TIER over-claim gate (issue #106). Upstream gates a class's
# default `posture:` on the receiver's typing — `posture_allowed?` refuses it
# whenever the typer called the receiver `Dynamic` — and the reference cannot
# resolve every constant its own catalogue names. A typer-free port has no such
# bit, so an unconditional posture tier proves labels the oracle does not, which
# is an OVER and a false positive in waiting (ADR-0043 § 4).
#
# WHICH constants the oracle resolves is deliberately not encoded here: it is a
# function of the reference's RBS environment and moves with the pin AND with
# the machine, and mirroring it is forbidden (ADR-0043 § 1). The project probes
# EVERY catalogued class and lets the differential report the answer.
#
# `Posture#c_*` isolates the posture tier. `Row#r_*` and `Universal#u_*` are the
# must-still-fire controls for the two tiers consulted BEFORE it, so a port
# cannot pass by dropping the catalogue altogether.

# --- the posture tier, isolated ----------------------------------------------
#
# One method per class carrying a `posture:` (80 of 80).
# `zz_uncatalogued_zz` is rowed by no class and is not a universal name, so a
# proven label here can only have come from the class default. A class whose
# posture resolves to ∅ is included anyway: it is an exhaustiveness probe for
# the taint slice, and the set of classes is the catalogue's, not a curated one.

class Posture
  # posture: stdin
  def c_argf
    ARGF.zz_uncatalogued_zz
  end

  # posture: net
  def c_addrinfo
    Addrinfo.zz_uncatalogued_zz
  end

  # posture: value
  def c_array
    Array.zz_uncatalogued_zz
  end

  # posture: net
  def c_basicsocket
    BasicSocket.zz_uncatalogued_zz
  end

  # posture: value
  def c_class
    Class.zz_uncatalogued_zz
  end

  # posture: value
  def c_comparable
    Comparable.zz_uncatalogued_zz
  end

  # posture: value
  def c_complex
    Complex.zz_uncatalogued_zz
  end

  # posture: value
  def c_conditionvariable
    ConditionVariable.zz_uncatalogued_zz
  end

  # posture: value
  def c_data
    Data.zz_uncatalogued_zz
  end

  # posture: value
  def c_date
    Date.zz_uncatalogued_zz
  end

  # posture: value
  def c_datetime
    DateTime.zz_uncatalogued_zz
  end

  # posture: fs
  def c_dir
    Dir.zz_uncatalogued_zz
  end

  # posture: global
  def c_env
    ENV.zz_uncatalogued_zz
  end

  # posture: value
  def c_encoding
    Encoding.zz_uncatalogued_zz
  end

  # posture: value
  def c_enumerable
    Enumerable.zz_uncatalogued_zz
  end

  # posture: value
  def c_enumerator
    Enumerator.zz_uncatalogued_zz
  end

  # posture: value
  def c_falseclass
    FalseClass.zz_uncatalogued_zz
  end

  # posture: value
  def c_fiber
    Fiber.zz_uncatalogued_zz
  end

  # posture: value
  def c_fiddle__function
    Fiddle::Function.zz_uncatalogued_zz
  end

  # posture: ffi
  def c_fiddle__handle
    Fiddle::Handle.zz_uncatalogued_zz
  end

  # posture: fs
  def c_file
    File.zz_uncatalogued_zz
  end

  # posture: fs
  def c_fileutils
    FileUtils.zz_uncatalogued_zz
  end

  # posture: value
  def c_float
    Float.zz_uncatalogued_zz
  end

  # posture: global
  def c_gc
    GC.zz_uncatalogued_zz
  end

  # posture: value
  def c_hash
    Hash.zz_uncatalogued_zz
  end

  # posture: world
  def c_io
    IO.zz_uncatalogued_zz
  end

  # posture: value
  def c_integer
    Integer.zz_uncatalogued_zz
  end

  # posture: world
  def c_kernel
    Kernel.zz_uncatalogued_zz
  end

  # posture: value
  def c_logger
    Logger.zz_uncatalogued_zz
  end

  # posture: value
  def c_matchdata
    MatchData.zz_uncatalogued_zz
  end

  # posture: value
  def c_method
    Method.zz_uncatalogued_zz
  end

  # posture: value
  def c_module
    Module.zz_uncatalogued_zz
  end

  # posture: value
  def c_monitor
    Monitor.zz_uncatalogued_zz
  end

  # posture: value
  def c_mutex
    Mutex.zz_uncatalogued_zz
  end

  # posture: net
  def c_net__ftp
    Net::FTP.zz_uncatalogued_zz
  end

  # posture: http
  def c_net__http
    Net::HTTP.zz_uncatalogued_zz
  end

  # posture: net
  def c_net__smtp
    Net::SMTP.zz_uncatalogued_zz
  end

  # posture: value
  def c_nilclass
    NilClass.zz_uncatalogued_zz
  end

  # posture: value
  def c_numeric
    Numeric.zz_uncatalogued_zz
  end

  # posture: value
  def c_object
    Object.zz_uncatalogued_zz
  end

  # posture: global
  def c_objectspace
    ObjectSpace.zz_uncatalogued_zz
  end

  # posture: process
  def c_open3
    Open3.zz_uncatalogued_zz
  end

  # posture: net
  def c_openssl__ssl__sslsocket
    OpenSSL::SSL::SSLSocket.zz_uncatalogued_zz
  end

  # posture: value
  def c_openuri
    OpenURI.zz_uncatalogued_zz
  end

  # posture: process
  def c_pty
    PTY.zz_uncatalogued_zz
  end

  # posture: value
  def c_pathname
    Pathname.zz_uncatalogued_zz
  end

  # posture: value
  def c_proc
    Proc.zz_uncatalogued_zz
  end

  # posture: process
  def c_process
    Process.zz_uncatalogued_zz
  end

  # posture: value
  def c_queue
    Queue.zz_uncatalogued_zz
  end

  # posture: value
  def c_ractor
    Ractor.zz_uncatalogued_zz
  end

  # posture: value
  def c_random
    Random.zz_uncatalogued_zz
  end

  # posture: value
  def c_range
    Range.zz_uncatalogued_zz
  end

  # posture: value
  def c_rational
    Rational.zz_uncatalogued_zz
  end

  # posture: value
  def c_regexp
    Regexp.zz_uncatalogued_zz
  end

  # posture: net
  def c_resolv
    Resolv.zz_uncatalogued_zz
  end

  # posture: net
  def c_resolv__dns
    Resolv::DNS.zz_uncatalogued_zz
  end

  # posture: net
  def c_sockssocket
    SOCKSSocket.zz_uncatalogued_zz
  end

  # posture: stderr
  def c_stderr
    STDERR.zz_uncatalogued_zz
  end

  # posture: stdin
  def c_stdin
    STDIN.zz_uncatalogued_zz
  end

  # posture: stdout
  def c_stdout
    STDOUT.zz_uncatalogued_zz
  end

  # posture: nondet
  def c_securerandom
    SecureRandom.zz_uncatalogued_zz
  end

  # posture: value
  def c_set
    Set.zz_uncatalogued_zz
  end

  # posture: signal
  def c_signal
    Signal.zz_uncatalogued_zz
  end

  # posture: value
  def c_sizedqueue
    SizedQueue.zz_uncatalogued_zz
  end

  # posture: net
  def c_socket
    Socket.zz_uncatalogued_zz
  end

  # posture: value
  def c_string
    String.zz_uncatalogued_zz
  end

  # posture: value
  def c_stringio
    StringIO.zz_uncatalogued_zz
  end

  # posture: value
  def c_struct
    Struct.zz_uncatalogued_zz
  end

  # posture: value
  def c_symbol
    Symbol.zz_uncatalogued_zz
  end

  # posture: net
  def c_tcpserver
    TCPServer.zz_uncatalogued_zz
  end

  # posture: net
  def c_tcpsocket
    TCPSocket.zz_uncatalogued_zz
  end

  # posture: fs
  def c_tempfile
    Tempfile.zz_uncatalogued_zz
  end

  # posture: value
  def c_thread
    Thread.zz_uncatalogued_zz
  end

  # posture: value
  def c_time
    Time.zz_uncatalogued_zz
  end

  # posture: value
  def c_trueclass
    TrueClass.zz_uncatalogued_zz
  end

  # posture: net
  def c_udpsocket
    UDPSocket.zz_uncatalogued_zz
  end

  # posture: ipc
  def c_unixserver
    UNIXServer.zz_uncatalogued_zz
  end

  # posture: ipc
  def c_unixsocket
    UNIXSocket.zz_uncatalogued_zz
  end

  # posture: value
  def c_uri
    URI.zz_uncatalogued_zz
  end

  # posture: value
  def c_warning
    Warning.zz_uncatalogued_zz
  end
end

# --- control: the ROW tier still answers -------------------------------------
#
# `Catalog#lookup` reads a row BEFORE it consults the posture, and a row is
# authoritative whatever the typer thinks of the receiver — `Net::HTTP.get` is
# proven `io.net.http` by the oracle even though `Net::HTTP` is exactly the
# constant it cannot resolve. These must stay MATCH.

class Row
  # Date: nondet.time
  def r_date
    Date.today
  end

  # DateTime: nondet.time
  def r_datetime
    DateTime.now
  end

  # Dir: global.write
  def r_dir
    Dir.chdir
  end

  # ENV: global.write
  def r_env
    ENV.clear
  end

  # Encoding: global.read
  def r_encoding
    Encoding.default_external
  end

  # File: io.fs.read
  def r_file
    File.atime
  end

  # FileUtils: global.write
  def r_fileutils
    FileUtils.cd
  end

  # GC: global.write
  def r_gc
    GC.compact
  end

  # IO: io.fs.read
  def r_io
    IO.binread
  end

  # Net::HTTP: io.net.http
  def r_net__http
    Net::HTTP.get
  end

  # ObjectSpace: global.read
  def r_objectspace
    ObjectSpace.count_objects
  end

  # Pathname: global.read
  def r_pathname
    Pathname.getwd
  end

  # Process: exit, io.output.stderr
  def r_process
    Process.abort
  end

  # Random: nondet.random
  def r_random
    Random.bytes
  end

  # SecureRandom: nondet.random
  def r_securerandom
    SecureRandom.alphanumeric
  end

  # Signal: io.signal
  def r_signal
    Signal.trap
  end

  # Tempfile: io.fs.write
  def r_tempfile
    Tempfile.create
  end

  # Time: global.read
  def r_time
    Time.local
  end

  # Warning: io.output.stderr
  def r_warning
    Warning.warn
  end
end

# --- control: the UNIVERSAL tier still answers, and still WINS ---------------
#
# The 34-name `universal:` list is consulted before the posture, and it answers
# ∅: `File.class` touches nothing, and the oracle proves nothing for it even
# though `File`'s posture is `io.fs`. Every class below has a NON-EMPTY posture,
# so a posture that ever leaked past the universal tier would show up here as an
# OVER rather than as silence.

class Universal
  def u_argf
    ARGF.class
  end

  def u_addrinfo
    Addrinfo.class
  end

  def u_basicsocket
    BasicSocket.class
  end

  def u_dir
    Dir.class
  end

  def u_env
    ENV.class
  end

  def u_fiddle__handle
    Fiddle::Handle.class
  end

  def u_file
    File.class
  end

  def u_fileutils
    FileUtils.class
  end

  def u_gc
    GC.class
  end

  def u_io
    IO.class
  end

  def u_kernel
    Kernel.class
  end

  def u_net__ftp
    Net::FTP.class
  end

  def u_net__http
    Net::HTTP.class
  end

  def u_net__smtp
    Net::SMTP.class
  end

  def u_objectspace
    ObjectSpace.class
  end

  def u_open3
    Open3.class
  end

  def u_openssl__ssl__sslsocket
    OpenSSL::SSL::SSLSocket.class
  end

  def u_pty
    PTY.class
  end

  def u_process
    Process.class
  end

  def u_resolv
    Resolv.class
  end

  def u_resolv__dns
    Resolv::DNS.class
  end

  def u_sockssocket
    SOCKSSocket.class
  end

  def u_stderr
    STDERR.class
  end

  def u_stdin
    STDIN.class
  end

  def u_stdout
    STDOUT.class
  end

  def u_securerandom
    SecureRandom.class
  end

  def u_signal
    Signal.class
  end

  def u_socket
    Socket.class
  end

  def u_tcpserver
    TCPServer.class
  end

  def u_tcpsocket
    TCPSocket.class
  end

  def u_tempfile
    Tempfile.class
  end

  def u_udpsocket
    UDPSocket.class
  end

  def u_unixserver
    UNIXServer.class
  end

  def u_unixsocket
    UNIXSocket.class
  end
end
